import type { InstrumentSpec } from '@otc/core';
import type { AssetDefinition, CalibrationEvidence } from './asset.js';
import type { MarketEngineConfig } from './factory.js';
import { personalityConfig } from './personality.js';

/**
 * The targets an asset's personality was authored to hit.
 *
 * Two traits cannot be chosen independently of an asset's rhythm — `clustering`,
 * because cascade depth is an exponent on tail weight, and `volatility`, because
 * depth also changes realised amplitude. Both are solved for by
 * `authorPersonality`, so what is *chosen* is these two targets and what is
 * *recorded* is the traits they produced. `catalogue.test.ts` re-runs the
 * authoring and requires the recorded traits back.
 */
export interface AuthoringTargets {
  readonly excessKurtosis: number;
  /** RMS per-tick magnitude from base volatility and the cascade. */
  readonly tickRms: number;
  /**
   * The tail weight the family drew, before the brief retreated from it.
   *
   * **Cycle Audit 7, a3-05.** The brief steps a target down when the solve
   * cannot reach it, and the sampler clamps a draw to what the rhythm can
   * supply; both happened silently, so a registered asset could sit below its
   * family's band with a record that said only what was achieved. Absent on a
   * hand-authored asset; equal to {@link AuthoringTargets.excessKurtosis} when
   * nothing retreated.
   */
  readonly drawnExcessKurtosis?: number;
  /** Retreats the brief took from that draw. Absent on a hand-authored asset. */
  readonly retreats?: number;
  /**
   * The family's floor, present only when the rhythm drawn could not reach it
   * and the target was clamped *below* the band the archetype declares.
   */
  readonly clampedFrom?: number;
}

/**
 * An asset that has been through registration, with the evidence it produced.
 *
 * Registration is not repeated at startup. It is a deliberate act that produces
 * a lattice and a record of how that lattice was chosen, and the record is what
 * makes the choice auditable later. `catalogue.stat.test.ts` recalibrates every
 * asset here from different streams and fails if the recorded numbers do not
 * reproduce.
 */
export interface RegisteredAsset {
  readonly definition: AssetDefinition;
  readonly instrument: InstrumentSpec;
  readonly evidence: CalibrationEvidence;
  readonly authored: AuthoringTargets;
}

/**
 * Keyring label under which an asset's registration streams were derived.
 *
 * PH-10.1 §5.1: the analytic gate's structure term has no closed form and is
 * estimated by simulation, so the personality solve is exact only with respect
 * to the stream that drove it. Recording the label is what makes a registered
 * asset's tail weight reproducible rather than merely plausible.
 */
export function registrationKeyLabel(id: string): string {
  return `registration-${id}`;
}

/**
 * A compiled entry whose every number a run produced (PH-26.3).
 *
 * The five hand-authored assets were recorded by a `registered` helper that
 * fixed the calibration span and replicate count to the module defaults; it
 * went with them (PH-26.3). The thirty are produced by
 * `tools/sim/src/buildCatalogue.ts`, which calibrates each at the span its own
 * dispersion fit needs and records exactly that, so this takes the evidence
 * whole rather than assuming any of it.
 */
export function recorded(
  definition: AssetDefinition,
  authored: AuthoringTargets,
  lattice: { readonly logQuantum: number; readonly displayPrecision: number },
  evidence: CalibrationEvidence,
): RegisteredAsset {
  return {
    definition,
    authored,
    instrument: {
      id: definition.id,
      family: definition.family,
      logQuantum: lattice.logQuantum,
      displayPrecision: lattice.displayPrecision,
      referencePrice: definition.referencePrice,
    },
    evidence,
  };
}

/**
 * The asset catalogue: thirty assets, every number produced by a run.
 *
 * **PH-26.3.** The Human Owner asked for a library of thirty predefined OTC
 * assets — eight currency pairs, eight equities, six crypto pairs and eight
 * invented thematic indices — replacing the five hand-authored assets PH-4
 * built and PH-10 and PH-24.17 re-authored. Each asset's personality was drawn
 * from its **seat** (`seats.ts`) under a stream seeded by its own id, authored,
 * calibrated at three replicates of a third of the span its dispersion fit
 * needs, and differentiated against everything before it, by
 * `tools/sim/src/buildCatalogue.ts`:
 *
 * GENERATED by tools/sim/src/buildCatalogue.ts — do not edit by hand.
 * Regenerate with: npm run catalogue:build -- --replicates 3
 * Keyring: MasterKeyring.forTesting(registrationKeyLabel(id)) per asset; the draw derives under asset label `<id>`, the authoring under `registration-<id>`. Run label: catalogue-of-thirty-ph34. Run time: 7.7 minutes.
 *
 * **PH-34 (2026-09-22)** regenerated all thirty on the new market model —
 * regimes that last like a market's at levels above the real one, a floor
 * under calm, ticks that follow the regime — with each asset's tick rate fitted
 * to its character and its budget at OTC level (`OTC_DISPERSION_FACTOR`). Every
 * lattice below is the one PH-26.3 recorded, kept: a running market's prices
 * are integers on it (`buildCatalogue.ts`).
 *
 * Nothing below was typed. The evidence table the same run wrote is
 * `docs/evidence/PH-26-CATALOGUE-OF-THIRTY.md`, and `catalogue.stat.test.ts`
 * recalibrates a stratified sample of these at every gate.
 *
 * ## Decisions that are the Human Owner's
 *
 * Equities are declared in the existing `etf` family; no archetype and no
 * family was added; the five incumbents are gone. Their ids — `eurusd`,
 * `gbpjpy`, `btcusd`, `spx`, `xauusd` — are retired and never reused, because a
 * checkpoint written under an id must never be resumed by another personality
 * under that id (`packages/runtime/src/personality.ts` now refuses it, and the
 * ids make it impossible anyway).
 *
 * ## What the names mean
 *
 * Eight instruments carry the names of listed companies and twenty-two the
 * names of real currency and crypto pairs, at reference prices measured as the
 * August 2026 monthly average of each. The reference price is the origin of
 * the log lattice and nothing more: this market tracks nothing, and the `OTC`
 * suffix on every display name is the convention that says so. The eight
 * thematic indices are inventions of this product and open at 1,000 USDT.
 *
 * Every quantum below was derived, never chosen: the 1% quantile of that
 * asset's own 30-second continuous return distribution. The realised rate on
 * the published lattice is about half that — see `MEASURED_LATTICE_TIE_RATES`
 * — because a tie is an integer-price event and the calibration measures a
 * continuous proxy for it.
 */
export const ASSET_CATALOGUE: readonly RegisteredAsset[] = [
  recorded(
    {
      id: 'eurusd-otc',
      family: 'forex',
      displayName: 'EUR/USD OTC',
      referencePrice: 1.16,
      traits: {
        tempoMs: 1892.7272400294776,
        volatility: 0.000022331513682780187,
        clustering: 0.199733707117897,
        burstiness: 0.5686004158406961,
        regimeSpread: 0.9722267597484684,
        structureSpread: 1.0247632649957992,
        durationCoupling: 0.24849584307641298,
        cascadeDepth: 16,
        cascadeSpanMs: 147401773.69370702,
        cascadeSpacing: 1.967557681850178,
        regimeTempo: 1.914818009109728,
        arrivalMemoryMs: 387519.2406133858,
      },
    },
    {
      excessKurtosis: 51.74839887934493,
      tickRms: 0.00003053720256652392,
      drawnExcessKurtosis: 51.74839887934476,
      retreats: 0,
    },
    { logQuantum: 3.131447750503912e-7, displayPrecision: 7 },
    {
      predictedExcessKurtosis: 47.64767478483931,
      logQuantum: 5.716968584684e-7,
      tieRate: 0.01005063099826192,
      medianSteps: 69.99099026365151,
      meanIntervalMs: 968.4663278814363,
      logVariancePerMs: 5.366718106995883e-13,
      horizonMs: 30000,
      simulatedMs: 794004221,
      replicates: 3,
      horizons: 79398,
      volatilityScale: 2.1837783938990554,
    },
  ),
  recorded(
    {
      id: 'gbpusd-otc',
      family: 'forex',
      displayName: 'GBP/USD OTC',
      referencePrice: 1.35,
      traits: {
        tempoMs: 2056.7283781484175,
        volatility: 0.000015382800752494412,
        clustering: 0.27573869946596063,
        burstiness: 0.6361004973160823,
        regimeSpread: 1.0766293230364432,
        structureSpread: 0.9320257959606826,
        durationCoupling: 0.28671737458600555,
        cascadeDepth: 11,
        cascadeSpanMs: 90061553.05699967,
        cascadeSpacing: 2.6549445988340765,
        regimeTempo: 1.2422406366910805,
        arrivalMemoryMs: 204943.36773474203,
      },
    },
    {
      excessKurtosis: 72.67489029278565,
      tickRms: 0.000023018316992949073,
      drawnExcessKurtosis: 72.67489029278565,
      retreats: 0,
    },
    { logQuantum: 2.896342933171461e-7, displayPrecision: 7 },
    {
      predictedExcessKurtosis: 70.23733352236684,
      logQuantum: 5.575656685233962e-7,
      tieRate: 0.011337167357203224,
      medianSteps: 60.666365386239434,
      meanIntervalMs: 912.0991756358208,
      logVariancePerMs: 6.871926440329217e-13,
      horizonMs: 30000,
      simulatedMs: 485131566,
      replicates: 3,
      horizons: 48513,
      volatilityScale: 1.5003384427314057,
    },
  ),
  recorded(
    {
      id: 'usdjpy-otc',
      family: 'forex',
      displayName: 'USD/JPY OTC',
      referencePrice: 159,
      traits: {
        tempoMs: 1885.3905155307211,
        volatility: 0.000021394476491515748,
        clustering: 0.2338477043851805,
        burstiness: 0.6039380190116258,
        regimeSpread: 1.06978151041035,
        structureSpread: 0.9284707356627397,
        durationCoupling: 0.2246043783756686,
        cascadeDepth: 14,
        cascadeSpanMs: 124987835.064402,
        cascadeSpacing: 2.3747104347647476,
        regimeTempo: 1.5299139831411468,
        arrivalMemoryMs: 159671.75030461754,
      },
    },
    {
      excessKurtosis: 63.38880622682403,
      tickRms: 0.00003105705891929252,
      drawnExcessKurtosis: 63.3888062268239,
      retreats: 0,
    },
    { logQuantum: 4.1322131154383336e-7, displayPrecision: 5 },
    {
      predictedExcessKurtosis: 64.05285339271464,
      logQuantum: 6.500933493146342e-7,
      tieRate: 0.010857618156432878,
      medianSteps: 65.23026339625127,
      meanIntervalMs: 835.3164027444055,
      logVariancePerMs: 1.0049588477366256e-12,
      horizonMs: 30000,
      simulatedMs: 673267805,
      replicates: 3,
      horizons: 67326,
      volatilityScale: 1.7553948931368168,
    },
  ),
  recorded(
    {
      id: 'audusd-otc',
      family: 'forex',
      displayName: 'AUD/USD OTC',
      referencePrice: 0.71,
      traits: {
        tempoMs: 1963.2549397781188,
        volatility: 0.00002389112673893331,
        clustering: 0.23825417913979957,
        burstiness: 0.6350395009829765,
        regimeSpread: 1.1484795808642667,
        structureSpread: 1.1185192758125486,
        durationCoupling: 0.18459049348536957,
        cascadeDepth: 13,
        cascadeSpanMs: 103272337.29755306,
        cascadeSpacing: 2.5060311299649554,
        regimeTempo: 1.4421240027053064,
        arrivalMemoryMs: 187037.1234118007,
      },
    },
    {
      excessKurtosis: 70.86598208875398,
      tickRms: 0.00003420554486983164,
      drawnExcessKurtosis: 70.86598208875381,
      retreats: 0,
    },
    { logQuantum: 3.6733805244148213e-7, displayPrecision: 7 },
    {
      predictedExcessKurtosis: 68.54318799891378,
      logQuantum: 6.772471722639482e-7,
      tieRate: 0.01060597889589962,
      medianSteps: 72.21587560345606,
      meanIntervalMs: 778.4072302351386,
      logVariancePerMs: 1.250252057613169e-12,
      horizonMs: 30000,
      simulatedMs: 556293657,
      replicates: 3,
      horizons: 55629,
      volatilityScale: 1.7813224032611326,
    },
  ),
  recorded(
    {
      id: 'usdchf-otc',
      family: 'forex',
      displayName: 'USD/CHF OTC',
      referencePrice: 0.81,
      traits: {
        tempoMs: 1878.105437173051,
        volatility: 0.000012704731924559745,
        clustering: 0.22530709103914076,
        burstiness: 0.5256126291454096,
        regimeSpread: 0.9111136917379372,
        structureSpread: 0.981986405115825,
        durationCoupling: 0.26179931847852767,
        cascadeDepth: 13,
        cascadeSpanMs: 145831092.740785,
        cascadeSpacing: 2.2123092553896457,
        regimeTempo: 2.135877100162636,
        arrivalMemoryMs: 328284.42242269206,
      },
    },
    {
      excessKurtosis: 46.675647159011596,
      tickRms: 0.000017528602343809358,
      drawnExcessKurtosis: 46.67564715901146,
      retreats: 0,
    },
    { logQuantum: 3.228056739320868e-7, displayPrecision: 7 },
    {
      predictedExcessKurtosis: 47.18718224934757,
      logQuantum: 5.070147152048105e-7,
      tieRate: 0.012463081780222018,
      medianSteps: 56.15406095268421,
      meanIntervalMs: 1035.7745292244538,
      logVariancePerMs: 4.047337962962963e-13,
      horizonMs: 30000,
      simulatedMs: 785543487,
      replicates: 3,
      horizons: 78552,
      volatilityScale: 1.3934097532649723,
    },
  ),
  recorded(
    {
      id: 'eurgbp-otc',
      family: 'forex',
      displayName: 'EUR/GBP OTC',
      referencePrice: 0.856,
      traits: {
        tempoMs: 1989.4218468952704,
        volatility: 0.00001909378616839991,
        clustering: 0.2070876043273609,
        burstiness: 0.5468214169547922,
        regimeSpread: 1.0262965385532676,
        structureSpread: 1.1322742596486342,
        durationCoupling: 0.30484514889319614,
        cascadeDepth: 15,
        cascadeSpanMs: 109956936.0711137,
        cascadeSpacing: 2.092075364038772,
        regimeTempo: 1.762717737243383,
        arrivalMemoryMs: 274285.1737644539,
      },
    },
    {
      excessKurtosis: 60.29352793041021,
      tickRms: 0.000026161706759764935,
      drawnExcessKurtosis: 60.293527930410214,
      retreats: 0,
    },
    { logQuantum: 2.7286603356753726e-7, displayPrecision: 7 },
    {
      predictedExcessKurtosis: 59.301159327397954,
      logQuantum: 4.415807144384675e-7,
      tieRate: 0.009556129598676324,
      medianSteps: 70.19775972849544,
      meanIntervalMs: 1092.3017700300968,
      logVariancePerMs: 3.3449074074074066e-13,
      horizonMs: 30000,
      simulatedMs: 592301363,
      replicates: 3,
      horizons: 59229,
      volatilityScale: 2.2337889832374116,
    },
  ),
  recorded(
    {
      id: 'gbpjpy-otc',
      family: 'forex',
      displayName: 'GBP/JPY OTC',
      referencePrice: 215,
      traits: {
        tempoMs: 1112.8767704499,
        volatility: 0.000058737019278022304,
        clustering: 0.39522322224548934,
        burstiness: 0.6857773283992225,
        regimeSpread: 1.2954382195731176,
        structureSpread: 0.8730192594119726,
        durationCoupling: 0.3040141092050166,
        cascadeDepth: 6,
        cascadeSpanMs: 42813798.23860636,
        cascadeSpacing: 4.105971023360371,
        regimeTempo: 0.41490023799441395,
        arrivalMemoryMs: 26502.30308471578,
      },
    },
    {
      excessKurtosis: 54.758814753653866,
      tickRms: 0.00009078463904732888,
      drawnExcessKurtosis: 60.84312750405996,
      retreats: 1,
      clampedFrom: 120,
    },
    { logQuantum: 7.224507310547509e-7, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 56.12165183628543,
      logQuantum: 0.00000169323578144207,
      tieRate: 0.010381944444444444,
      medianSteps: 75.58056732035136,
      meanIntervalMs: 410.39340292604794,
      logVariancePerMs: 1.7179816100823044e-11,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 1.769703617194845,
    },
  ),
  recorded(
    {
      id: 'eurjpy-otc',
      family: 'forex',
      displayName: 'EUR/JPY OTC',
      referencePrice: 184,
      traits: {
        tempoMs: 1150.4657100287725,
        volatility: 0.0000394291613236899,
        clustering: 0.3196473804037251,
        burstiness: 0.5730426507629183,
        regimeSpread: 1.1027899483714698,
        structureSpread: 1.0932902455256868,
        durationCoupling: 0.19290762141446954,
        cascadeDepth: 9,
        cascadeSpanMs: 23480861.93597185,
        cascadeSpacing: 3.063182343697715,
        regimeTempo: 0.795528385547744,
        arrivalMemoryMs: 62192.111810422,
      },
    },
    {
      excessKurtosis: 85.16937131721079,
      tickRms: 0.00006108633396490181,
      drawnExcessKurtosis: 85.1693713172107,
      retreats: 0,
    },
    { logQuantum: 6.318992264722798e-7, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 85.23203881292305,
      logQuantum: 0.0000013351456718564061,
      tieRate: 0.010138888888888888,
      medianSteps: 80.66136106645538,
      meanIntervalMs: 484.73450967477345,
      logVariancePerMs: 8.362268518518519e-12,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 1.5598851735169745,
    },
  ),
  recorded(
    {
      id: 'aapl-otc',
      family: 'etf',
      displayName: 'Apple OTC',
      referencePrice: 310,
      traits: {
        tempoMs: 893.4829374519136,
        volatility: 0.00003944452814965021,
        clustering: 0.24882204242879286,
        burstiness: 0.4500253687203627,
        regimeSpread: 0.9211425277666317,
        structureSpread: 1.2750974748992998,
        durationCoupling: 0.22740622265143204,
        cascadeDepth: 10,
        cascadeSpanMs: 141460958.02249637,
        cascadeSpacing: 2.701158375806777,
        regimeTempo: 1.7922310393918115,
        arrivalMemoryMs: 361629.04836906376,
      },
    },
    {
      excessKurtosis: 52.60948912932605,
      tickRms: 0.0000532635665683534,
      drawnExcessKurtosis: 52.60948912932613,
      retreats: 0,
    },
    { logQuantum: 0.0000010382975411320733, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 50.43721928919601,
      logQuantum: 0.000001496297468909058,
      tieRate: 0.01010498687664042,
      medianSteps: 68.84282735146428,
      meanIntervalMs: 544.1589632932198,
      logVariancePerMs: 5.351851851851849e-12,
      horizonMs: 30000,
      simulatedMs: 762003028,
      replicates: 3,
      horizons: 76200,
      volatilityScale: 1.6079084647516053,
    },
  ),
  recorded(
    {
      id: 'msft-otc',
      family: 'etf',
      displayName: 'Microsoft OTC',
      referencePrice: 495,
      traits: {
        tempoMs: 930.0939627858504,
        volatility: 0.00003934687226632614,
        clustering: 0.2543029995816154,
        burstiness: 0.4354440102342018,
        regimeSpread: 0.88014454831829,
        structureSpread: 1.3299855096211497,
        durationCoupling: 0.22699941339496393,
        cascadeDepth: 9,
        cascadeSpanMs: 138271972.1133019,
        cascadeSpacing: 3.374734408722801,
        regimeTempo: 2.191524457962109,
        arrivalMemoryMs: 413187.6913292819,
      },
    },
    {
      excessKurtosis: 47.078216133009114,
      tickRms: 0.000052164832795140585,
      drawnExcessKurtosis: 47.07821613300918,
      retreats: 0,
    },
    { logQuantum: 8.772309550094163e-7, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 47.52823406104801,
      logQuantum: 0.0000014346803569695646,
      tieRate: 0.009854862313878707,
      medianSteps: 70.30063250279632,
      meanIntervalMs: 582.5222784344171,
      logVariancePerMs: 4.0975115740740736e-12,
      horizonMs: 30000,
      simulatedMs: 744825024,
      replicates: 3,
      horizons: 74481,
      volatilityScale: 1.7406155445947797,
    },
  ),
  recorded(
    {
      id: 'nvda-otc',
      family: 'etf',
      displayName: 'NVIDIA OTC',
      referencePrice: 220,
      traits: {
        tempoMs: 703.1140027132979,
        volatility: 0.00007603611730399612,
        clustering: 0.2857638637318315,
        burstiness: 0.5556645630966711,
        regimeSpread: 1.0789333294547927,
        structureSpread: 1.1334901140641112,
        durationCoupling: 0.3271398186252985,
        cascadeDepth: 9,
        cascadeSpanMs: 90771571.5269747,
        cascadeSpacing: 2.2118630750559207,
        regimeTempo: 1.3991846120552154,
        arrivalMemoryMs: 209182.25349751182,
      },
    },
    {
      excessKurtosis: 64.93191557134695,
      tickRms: 0.00010825056626729636,
      drawnExcessKurtosis: 64.9319155713468,
      retreats: 0,
    },
    { logQuantum: 0.0000017994793022770206, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 62.31151113363339,
      logQuantum: 0.000002427661982594323,
      tieRate: 0.00961263140671657,
      medianSteps: 85.41962101412567,
      meanIntervalMs: 372.4083873272316,
      logVariancePerMs: 2.512397119341564e-11,
      horizonMs: 30000,
      simulatedMs: 488956199,
      replicates: 3,
      horizons: 48894,
      volatilityScale: 1.8298571114934261,
    },
  ),
  recorded(
    {
      id: 'tsla-otc',
      family: 'etf',
      displayName: 'Tesla OTC',
      referencePrice: 340,
      traits: {
        tempoMs: 598.8520894754314,
        volatility: 0.00009468765354588382,
        clustering: 0.25981304254731075,
        burstiness: 0.5331560550183579,
        regimeSpread: 1.092497857631795,
        structureSpread: 1.1711156567974987,
        durationCoupling: 0.3394507018308368,
        cascadeDepth: 10,
        cascadeSpanMs: 73679202.6143589,
        cascadeSpacing: 2.9400894077244906,
        regimeTempo: 1.4776272172358955,
        arrivalMemoryMs: 291156.03223236755,
      },
    },
    {
      excessKurtosis: 62.591996804703186,
      tickRms: 0.0001312618446875237,
      drawnExcessKurtosis: 62.59199680470315,
      retreats: 0,
    },
    { logQuantum: 0.0000025479700000762076, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 61.201928561042365,
      logQuantum: 0.000004002530163817515,
      tieRate: 0.010809585002645703,
      medianSteps: 68.78821256561042,
      meanIntervalMs: 341.02232437072365,
      logVariancePerMs: 3.3449074074074076e-11,
      horizonMs: 30000,
      simulatedMs: 396885305,
      replicates: 3,
      horizons: 39687,
      volatilityScale: 1.993033389716435,
    },
  ),
  recorded(
    {
      id: 'meta-otc',
      family: 'etf',
      displayName: 'Meta OTC',
      referencePrice: 575,
      traits: {
        tempoMs: 700.2178549813253,
        volatility: 0.00006221367060032831,
        clustering: 0.23166321720849786,
        burstiness: 0.4907503682434591,
        regimeSpread: 0.9339532575271764,
        structureSpread: 1.3929145448592113,
        durationCoupling: 0.283404261331114,
        cascadeDepth: 11,
        cascadeSpanMs: 117342208.15545748,
        cascadeSpacing: 2.5964503319129175,
        regimeTempo: 1.602801981459484,
        arrivalMemoryMs: 319090.2001480793,
      },
    },
    {
      excessKurtosis: 59.03004566356668,
      tickRms: 0.00008293852845018384,
      drawnExcessKurtosis: 59.03004566356671,
      retreats: 0,
    },
    { logQuantum: 0.000001635048966433398, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 60.36733155330637,
      logQuantum: 0.0000029103451804938277,
      tieRate: 0.009840682202920562,
      medianSteps: 70.04181236508244,
      meanIntervalMs: 413.8941133946497,
      logVariancePerMs: 1.6390046296296294e-11,
      horizonMs: 30000,
      simulatedMs: 632083362,
      replicates: 3,
      horizons: 63207,
      volatilityScale: 1.6455416034055785,
    },
  ),
  recorded(
    {
      id: 'amzn-otc',
      family: 'etf',
      displayName: 'Amazon OTC',
      referencePrice: 265,
      traits: {
        tempoMs: 800.5092352970438,
        volatility: 0.000053779311167249785,
        clustering: 0.2240529081460622,
        burstiness: 0.48700089136254265,
        regimeSpread: 0.9882636681569292,
        structureSpread: 1.258021665950809,
        durationCoupling: 0.2243972736963484,
        cascadeDepth: 12,
        cascadeSpanMs: 96813432.14325012,
        cascadeSpacing: 2.396246963589943,
        regimeTempo: 1.8793904654031315,
        arrivalMemoryMs: 293205.2527692481,
      },
    },
    {
      excessKurtosis: 53.674639298612846,
      tickRms: 0.00007215170339770141,
      drawnExcessKurtosis: 53.67463929861283,
      retreats: 0,
    },
    { logQuantum: 0.0000011106876236673, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 51.21850829259802,
      logQuantum: 0.0000028902409076224736,
      tieRate: 0.01083434006404725,
      medianSteps: 61.549294787640996,
      meanIntervalMs: 459.2747105580588,
      logVariancePerMs: 1.0740869341563791e-11,
      horizonMs: 30000,
      simulatedMs: 521501688,
      replicates: 3,
      horizons: 52149,
      volatilityScale: 1.6773624243810172,
    },
  ),
  recorded(
    {
      id: 'pbr-otc',
      family: 'etf',
      displayName: 'Petrobras OTC',
      referencePrice: 18.4,
      traits: {
        tempoMs: 805.370059799593,
        volatility: 0.00005211312490742842,
        clustering: 0.25201373351552114,
        burstiness: 0.548236574687773,
        regimeSpread: 1.0432440002115073,
        structureSpread: 1.1159142395960095,
        durationCoupling: 0.3042779476014586,
        cascadeDepth: 11,
        cascadeSpanMs: 73822502.8797999,
        cascadeSpacing: 2.747893867733064,
        regimeTempo: 1.4909880134451858,
        arrivalMemoryMs: 182497.64544208025,
      },
    },
    {
      excessKurtosis: 57.86536165956785,
      tickRms: 0.00007311859954298642,
      drawnExcessKurtosis: 57.86536165956785,
      retreats: 0,
    },
    { logQuantum: 0.0000015278920853002827, displayPrecision: 5 },
    {
      predictedExcessKurtosis: 60.049053890448775,
      logQuantum: 0.0000026214853762487923,
      tieRate: 0.011643405004400855,
      medianSteps: 61.953569214106395,
      meanIntervalMs: 428.5207056211902,
      logVariancePerMs: 1.3416795267489712e-11,
      horizonMs: 30000,
      simulatedMs: 397657216,
      replicates: 3,
      horizons: 39765,
      volatilityScale: 1.5637944816959155,
    },
  ),
  recorded(
    {
      id: 'nu-otc',
      family: 'etf',
      displayName: 'Nubank OTC',
      referencePrice: 14.4,
      traits: {
        tempoMs: 595.5639342012131,
        volatility: 0.00008445996832383641,
        clustering: 0.30569242142463315,
        burstiness: 0.5082893571475382,
        regimeSpread: 1.0378888054750472,
        structureSpread: 1.1076478837551782,
        durationCoupling: 0.29980194155716217,
        cascadeDepth: 8,
        cascadeSpanMs: 117911966.74169706,
        cascadeSpacing: 3.228004367598419,
        regimeTempo: 1.4408770836888893,
        arrivalMemoryMs: 190952.96352981715,
      },
    },
    {
      excessKurtosis: 56.48171645086925,
      tickRms: 0.00012073779063745921,
      drawnExcessKurtosis: 56.48171645086944,
      retreats: 0,
    },
    { logQuantum: 0.0000021676653092782303, displayPrecision: 5 },
    {
      predictedExcessKurtosis: 56.67372045635315,
      logQuantum: 0.00000399620957575971,
      tieRate: 0.011163068978004504,
      medianSteps: 65.60568147169231,
      meanIntervalMs: 331.6875454328972,
      logVariancePerMs: 3.805761316872428e-11,
      horizonMs: 30000,
      simulatedMs: 635152461,
      replicates: 3,
      horizons: 63513,
      volatilityScale: 1.7466172823154684,
    },
  ),
  recorded(
    {
      id: 'btcusdt-otc',
      family: 'crypto',
      displayName: 'BTC/USDT OTC',
      referencePrice: 70_000,
      traits: {
        tempoMs: 1012.7038297716356,
        volatility: 0.0000995009196598915,
        clustering: 0.23262127071172173,
        burstiness: 0.7220786749171393,
        regimeSpread: 1.2713434035603812,
        structureSpread: 0.9207727097424919,
        durationCoupling: 0.22488694928580782,
        cascadeDepth: 17,
        cascadeSpanMs: 128646905.7664875,
        cascadeSpacing: 1.9013373006643652,
        regimeTempo: 0.48747317327202216,
        arrivalMemoryMs: 29024.618373211953,
      },
    },
    {
      excessKurtosis: 116.92560128107294,
      tickRms: 0.00015572804384010393,
      drawnExcessKurtosis: 116.92560128107327,
      retreats: 0,
    },
    { logQuantum: 0.0000017544005781582127, displayPrecision: 1 },
    {
      predictedExcessKurtosis: 112.25468168187236,
      logQuantum: 0.0000029958268783988776,
      tieRate: 0.011616664502070797,
      medianSteps: 70.9083602034093,
      meanIntervalMs: 325.60869144378444,
      logVariancePerMs: 4.296347736625516e-11,
      horizonMs: 30000,
      simulatedMs: 692978000,
      replicates: 3,
      horizons: 69297,
      volatilityScale: 2.1526560933652763,
    },
  ),
  recorded(
    {
      id: 'ethusdt-otc',
      family: 'crypto',
      displayName: 'ETH/USDT OTC',
      referencePrice: 2_100,
      traits: {
        tempoMs: 943.0778269546685,
        volatility: 0.0001266539526806356,
        clustering: 0.2548179226117816,
        burstiness: 0.7972777987110796,
        regimeSpread: 1.4209645775934465,
        structureSpread: 1.0339365321308716,
        durationCoupling: 0.2741459614922707,
        cascadeDepth: 15,
        cascadeSpanMs: 103871390.15977749,
        cascadeSpacing: 2.123307134860964,
        regimeTempo: 0.3055371754370963,
        arrivalMemoryMs: 19950.315719723258,
      },
    },
    {
      excessKurtosis: 152.58245083728167,
      tickRms: 0.00020301744551138985,
      drawnExcessKurtosis: 152.58245083728178,
      retreats: 0,
    },
    { logQuantum: 0.0000016192151603799536, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 152.10559655952443,
      logQuantum: 0.0000036011289752487633,
      tieRate: 0.009597855227882037,
      medianSteps: 87.03439462480597,
      meanIntervalMs: 285.51526595828824,
      logVariancePerMs: 7.195267489711933e-11,
      horizonMs: 30000,
      simulatedMs: 559520555,
      replicates: 3,
      horizons: 55950,
      volatilityScale: 2.3129213439219205,
    },
  ),
  recorded(
    {
      id: 'bnbusdt-otc',
      family: 'crypto',
      displayName: 'BNB/USDT OTC',
      referencePrice: 650,
      traits: {
        tempoMs: 861.5309871955743,
        volatility: 0.0001261410205607649,
        clustering: 0.24631966778067665,
        burstiness: 0.7469353321375733,
        regimeSpread: 1.3099848481733545,
        structureSpread: 1.0869161042797584,
        durationCoupling: 0.3402085344931937,
        cascadeDepth: 15,
        cascadeSpanMs: 88110341.17071961,
        cascadeSpacing: 1.9999132967374997,
        regimeTempo: 0.40444878060427125,
        arrivalMemoryMs: 21180.543355418667,
      },
    },
    {
      excessKurtosis: 137.02364768508008,
      tickRms: 0.00019620896952338843,
      drawnExcessKurtosis: 137.02364768508,
      retreats: 0,
    },
    { logQuantum: 0.000001939892365940817, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 138.41468099374745,
      logQuantum: 0.000003735934010822002,
      tieRate: 0.00969237252423093,
      medianSteps: 74.73549671204121,
      meanIntervalMs: 299.5075559306304,
      logVariancePerMs: 5.94650205761317e-11,
      horizonMs: 30000,
      simulatedMs: 474621038,
      replicates: 3,
      horizons: 47460,
      volatilityScale: 2.4009928994880503,
    },
  ),
  recorded(
    {
      id: 'solusdt-otc',
      family: 'crypto',
      displayName: 'SOL/USDT OTC',
      referencePrice: 85,
      traits: {
        tempoMs: 691.4174399452849,
        volatility: 0.00016349802555246017,
        clustering: 0.37510527851810405,
        burstiness: 0.8171079017304319,
        regimeSpread: 1.385665185565065,
        structureSpread: 0.9474363420652783,
        durationCoupling: 0.47908466213582923,
        cascadeDepth: 8,
        cascadeSpanMs: 14243617.084324839,
        cascadeSpacing: 3.265774339795158,
        regimeTempo: 0.4904738399549584,
        arrivalMemoryMs: 27435.656370368593,
      },
    },
    {
      excessKurtosis: 144.5027301940978,
      tickRms: 0.0002768243726903032,
      drawnExcessKurtosis: 144.50273019409792,
      retreats: 0,
    },
    { logQuantum: 0.0000034472860125230552, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 137.20972018897075,
      logQuantum: 0.000005216116806758139,
      tieRate: 0.010208333333333333,
      medianSteps: 82.76756323589264,
      meanIntervalMs: 244.4776073791491,
      logVariancePerMs: 1.2937358539094648e-10,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 2.5309427878876476,
    },
  ),
  recorded(
    {
      id: 'xrpusdt-otc',
      family: 'crypto',
      displayName: 'XRP/USDT OTC',
      referencePrice: 1.2,
      traits: {
        tempoMs: 747.7422146004932,
        volatility: 0.0001412530850679476,
        clustering: 0.34303390823470215,
        burstiness: 0.7468900313314695,
        regimeSpread: 1.277945624547593,
        structureSpread: 1.1419700245951614,
        durationCoupling: 0.3428495605461378,
        cascadeDepth: 9,
        cascadeSpanMs: 16580828.760966431,
        cascadeSpacing: 2.706348618200529,
        regimeTempo: 0.522601052092699,
        arrivalMemoryMs: 43540.18230900274,
      },
    },
    {
      excessKurtosis: 136.31636402692388,
      tickRms: 0.00023303066272296395,
      drawnExcessKurtosis: 136.31636402692394,
      retreats: 0,
    },
    { logQuantum: 0.0000020345814952792886, displayPrecision: 6 },
    {
      predictedExcessKurtosis: 141.99349427704817,
      logQuantum: 0.000005159020799986954,
      tieRate: 0.0115625,
      medianSteps: 67.88614233847495,
      meanIntervalMs: 262.5882018269939,
      logVariancePerMs: 1.0439827674897122e-10,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 2.308995999047655,
    },
  ),
  recorded(
    {
      id: 'dogeusdt-otc',
      family: 'crypto',
      displayName: 'DOGE/USDT OTC',
      referencePrice: 0.078,
      traits: {
        tempoMs: 645.2933081818452,
        volatility: 0.00018911939719263636,
        clustering: 0.39045284769456534,
        burstiness: 0.8698176950362948,
        regimeSpread: 1.4499198385651457,
        structureSpread: 0.8378234649824825,
        durationCoupling: 0.6073960251478318,
        cascadeDepth: 7,
        cascadeSpanMs: 6370365.419998091,
        cascadeSpacing: 3.8848631745884292,
        regimeTempo: 0.35090506158931006,
        arrivalMemoryMs: 15589.486342561086,
      },
    },
    {
      excessKurtosis: 120.85659353185554,
      tickRms: 0.00031075485099766725,
      drawnExcessKurtosis: 134.28510392428393,
      retreats: 1,
      clampedFrom: 150,
    },
    { logQuantum: 0.000003528291226936427, displayPrecision: 7 },
    {
      predictedExcessKurtosis: 120.04043133345948,
      logQuantum: 0.000007614064035056906,
      tieRate: 0.009756944444444445,
      medianSteps: 79.08197545675911,
      meanIntervalMs: 236.8667139486257,
      logVariancePerMs: 1.6189351851851855e-10,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 2.612022884200981,
    },
  ),
  recorded(
    {
      id: 'mmx-idx-otc',
      family: 'crypto',
      displayName: 'MMX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 677.561959179303,
        volatility: 0.00022343970006201628,
        clustering: 0.3277812407537074,
        burstiness: 0.8416366994314232,
        regimeSpread: 1.4060355669840057,
        structureSpread: 1.1422891332683482,
        durationCoupling: 0.5091753057338805,
        cascadeDepth: 9,
        cascadeSpanMs: 16074586.626181249,
        cascadeSpacing: 2.6575030907913995,
        regimeTempo: 0.5739372503145908,
        arrivalMemoryMs: 41334.264992063465,
      },
    },
    {
      excessKurtosis: 149.86300161239114,
      tickRms: 0.00035367325735464095,
      drawnExcessKurtosis: 149.8630016123912,
      retreats: 0,
    },
    { logQuantum: 0.000004108423145417696, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 151.20059747635833,
      logQuantum: 0.0000058855122319195845,
      tieRate: 0.009479166666666667,
      medianSteps: 86.07071096550912,
      meanIntervalMs: 241.54650147569816,
      logVariancePerMs: 1.4286471193415636e-10,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 3.1154835860019765,
    },
  ),
  recorded(
    {
      id: 'cgx-idx-otc',
      family: 'crypto',
      displayName: 'CGX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 1004.6633317517651,
        volatility: 0.00010448377694737052,
        clustering: 0.2299578917480692,
        burstiness: 0.7841519450237221,
        regimeSpread: 1.3732092963592206,
        structureSpread: 1.0861910600969085,
        durationCoupling: 0.2806660978111063,
        cascadeDepth: 16,
        cascadeSpanMs: 127507297.07389174,
        cascadeSpacing: 1.8872042037933296,
        regimeTempo: 0.48066099995659256,
        arrivalMemoryMs: 25461.206040510147,
      },
    },
    {
      excessKurtosis: 120.3683515775111,
      tickRms: 0.000157790901618809,
      drawnExcessKurtosis: 120.36835157751123,
      retreats: 0,
    },
    { logQuantum: 0.0000012807165634409132, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 121.18205657764362,
      logQuantum: 0.000003785080895007029,
      tieRate: 0.010162779185230482,
      medianSteps: 75.63506084190621,
      meanIntervalMs: 309.851992787376,
      logVariancePerMs: 5.366718106995884e-11,
      horizonMs: 30000,
      simulatedMs: 686839307,
      replicates: 3,
      horizons: 68682,
      volatilityScale: 2.006602146991102,
    },
  ),
  recorded(
    {
      id: 'aix-idx-otc',
      family: 'index',
      displayName: 'AIX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 728.370746812484,
        volatility: 0.00006553741464296475,
        clustering: 0.23253709253834548,
        burstiness: 0.527661012773273,
        regimeSpread: 0.7807929928078016,
        structureSpread: 1.431616973622877,
        durationCoupling: 0.3046785755969861,
        cascadeDepth: 10,
        cascadeSpanMs: 162438862.37785017,
        cascadeSpacing: 3.175214092603512,
        regimeTempo: 2.7327022082053456,
        arrivalMemoryMs: 589114.5526163417,
      },
    },
    {
      excessKurtosis: 48.581838286052474,
      tickRms: 0.00008527932990772465,
      drawnExcessKurtosis: 48.58183828605249,
      retreats: 0,
    },
    { logQuantum: 0.0000018832316016661937, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 47.93192116785275,
      logQuantum: 0.0000029760772845524154,
      tieRate: 0.010160232233879631,
      medianSteps: 69.26964416254978,
      meanIntervalMs: 422.65804126186276,
      logVariancePerMs: 1.4866255144032924e-11,
      horizonMs: 30000,
      simulatedMs: 875004006,
      replicates: 3,
      horizons: 87498,
      volatilityScale: 1.7550451548754225,
    },
  ),
  recorded(
    {
      id: 'tcx-idx-otc',
      family: 'index',
      displayName: 'TCX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 823.1648404222001,
        volatility: 0.00004077277532670287,
        clustering: 0.2682087913298571,
        burstiness: 0.4399061999364536,
        regimeSpread: 0.8874283155193491,
        structureSpread: 1.2153618173375587,
        durationCoupling: 0.21296312294862646,
        cascadeDepth: 8,
        cascadeSpanMs: 139235927.3681038,
        cascadeSpacing: 3.7179380035729364,
        regimeTempo: 2.244307444393512,
        arrivalMemoryMs: 317523.17676743085,
      },
    },
    {
      excessKurtosis: 38.82822616238599,
      tickRms: 0.00005383263380857376,
      drawnExcessKurtosis: 38.828226162385924,
      retreats: 0,
    },
    { logQuantum: 0.0000012266628970962221, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 37.89309439905441,
      logQuantum: 0.0000017926094142314459,
      tieRate: 0.009613333333333333,
      medianSteps: 75.50996071525442,
      meanIntervalMs: 505.7765268530713,
      logVariancePerMs: 7.284465020576134e-12,
      horizonMs: 30000,
      simulatedMs: 750017529,
      replicates: 3,
      horizons: 75000,
      volatilityScale: 1.4476601315382864,
    },
  ),
  recorded(
    {
      id: 'scx-idx-otc',
      family: 'index',
      displayName: 'SCX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 694.8755690361907,
        volatility: 0.00008198663532885894,
        clustering: 0.2795611945159887,
        burstiness: 0.5506165404927515,
        regimeSpread: 0.9258311359115483,
        structureSpread: 1.2831754502075932,
        durationCoupling: 0.2942750830327222,
        cascadeDepth: 7,
        cascadeSpanMs: 137820171.82658166,
        cascadeSpacing: 3.7897671146367884,
        regimeTempo: 1.9744098500564375,
        arrivalMemoryMs: 589531.9701971862,
      },
    },
    {
      excessKurtosis: 39.59347045607203,
      tickRms: 0.0001066906863465409,
      drawnExcessKurtosis: 39.593470456072,
      retreats: 0,
    },
    { logQuantum: 0.000002327597824791533, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 39.83289372802251,
      logQuantum: 0.000003774674024074394,
      tieRate: 0.009967940946684985,
      medianSteps: 66.50297454599867,
      meanIntervalMs: 385.3578197822094,
      logVariancePerMs: 2.1407407407407405e-11,
      horizonMs: 30000,
      simulatedMs: 742391326,
      replicates: 3,
      horizons: 74238,
      volatilityScale: 1.9150719269792316,
    },
  ),
  recorded(
    {
      id: 'gmx-idx-otc',
      family: 'etf',
      displayName: 'GMX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 845.8114471049345,
        volatility: 0.00006637925638009006,
        clustering: 0.3024717224234844,
        burstiness: 0.550559179813238,
        regimeSpread: 0.8931146109392845,
        structureSpread: 1.3116939989623744,
        durationCoupling: 0.23209911711567402,
        cascadeDepth: 8,
        cascadeSpanMs: 79501844.52784836,
        cascadeSpacing: 2.2795813499878594,
        regimeTempo: 1.3785620633030269,
        arrivalMemoryMs: 183961.9829105928,
      },
    },
    {
      excessKurtosis: 65.4636179758605,
      tickRms: 0.00009421283299312715,
      drawnExcessKurtosis: 65.4636179758605,
      retreats: 0,
    },
    { logQuantum: 0.0000015098297855443824, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 64.74395385451948,
      logQuantum: 0.000002459217934778709,
      tieRate: 0.009667476181580422,
      medianSteps: 71.11322512776263,
      meanIntervalMs: 409.2135924865857,
      logVariancePerMs: 1.7988168724279835e-11,
      horizonMs: 30000,
      simulatedMs: 428249936,
      replicates: 3,
      horizons: 42824,
      volatilityScale: 1.805136571545623,
    },
  ),
  recorded(
    {
      id: 'evx-idx-otc',
      family: 'etf',
      displayName: 'EVX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 553.6915626682679,
        volatility: 0.00007787427751927214,
        clustering: 0.22969213553462903,
        burstiness: 0.47648412126411704,
        regimeSpread: 1.0966355945649306,
        structureSpread: 1.257184825677404,
        durationCoupling: 0.3304014623744861,
        cascadeDepth: 12,
        cascadeSpanMs: 137194201.65232572,
        cascadeSpacing: 2.9143528612443057,
        regimeTempo: 2.086904624664351,
        arrivalMemoryMs: 340256.0740542225,
      },
    },
    {
      excessKurtosis: 65.81976523612995,
      tickRms: 0.00010601480370697267,
      drawnExcessKurtosis: 65.81976523612995,
      retreats: 0,
    },
    { logQuantum: 0.0000028595178951219263, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 65.16581840420636,
      logQuantum: 0.0000049804477810861375,
      tieRate: 0.01013531799729364,
      medianSteps: 63.60628272576166,
      meanIntervalMs: 344.3540772345538,
      logVariancePerMs: 3.344907407407407e-11,
      horizonMs: 30000,
      simulatedMs: 739019433,
      replicates: 3,
      horizons: 73900,
      volatilityScale: 1.609691255636553,
    },
  ),
  recorded(
    {
      id: 'brx-idx-otc',
      family: 'etf',
      displayName: 'BRX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 731.2020201565134,
        volatility: 0.00005535600590993116,
        clustering: 0.22348215379122022,
        burstiness: 0.4299559829462449,
        regimeSpread: 0.9588801685103342,
        structureSpread: 1.3794547334064147,
        durationCoupling: 0.21804668624743972,
        cascadeDepth: 10,
        cascadeSpanMs: 86881609.66184996,
        cascadeSpacing: 3.3673831457402876,
        regimeTempo: 1.5207090725397223,
        arrivalMemoryMs: 242114.1168669156,
      },
    },
    {
      excessKurtosis: 42.5524073701624,
      tickRms: 0.00007063110361255585,
      drawnExcessKurtosis: 42.552407370162435,
      retreats: 0,
    },
    { logQuantum: 0.0000014896821412666174, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 42.3326838545821,
      logQuantum: 0.0000029449237648011193,
      tieRate: 0.010320512820512821,
      medianSteps: 63.52799713368715,
      meanIntervalMs: 456.84713006055796,
      logVariancePerMs: 1.0740869341563788e-11,
      horizonMs: 30000,
      simulatedMs: 468002271,
      replicates: 3,
      horizons: 46800,
      volatilityScale: 1.642011950005296,
    },
  ),
];

export function assetById(id: string): RegisteredAsset {
  const found = ASSET_CATALOGUE.find((asset) => asset.definition.id === id);
  if (found === undefined) {
    const known = ASSET_CATALOGUE.map((asset) => asset.definition.id).join(', ');
    throw new RangeError(`Unknown asset ${id}. The catalogue holds: ${known}.`);
  }
  return found;
}

/** The engine configuration for a registered asset. */
export function configFor(asset: RegisteredAsset): MarketEngineConfig {
  return { ...personalityConfig(asset.definition.traits), instrument: asset.instrument };
}
