import type { InstrumentSpec } from '@otc/core';
import type { AssetDefinition, CalibrationEvidence } from './asset.js';
import type { MarketEngineConfig } from './factory.js';
import { personalityConfig } from './personality.js';

/**
 * The targets an asset's personality was authored to hit.
 *
 * Two traits cannot be chosen independently of an asset's rhythm — `clustering`,
 * because cascade depth is an exponent on tail weight, and `volatility`, because
 * depth also changes realised amplitude. Both are solved for by
 * `authorPersonality`, so what is *chosen* is these two targets and what is
 * *recorded* is the traits they produced. `catalogue.test.ts` re-runs the
 * authoring and requires the recorded traits back.
 */
export interface AuthoringTargets {
  readonly excessKurtosis: number;
  /** RMS per-tick magnitude from base volatility and the cascade. */
  readonly tickRms: number;
  /**
   * The tail weight the family drew, before the brief retreated from it.
   *
   * **Cycle Audit 7, a3-05.** The brief steps a target down when the solve
   * cannot reach it, and the sampler clamps a draw to what the rhythm can
   * supply; both happened silently, so a registered asset could sit below its
   * family's band with a record that said only what was achieved. Absent on a
   * hand-authored asset; equal to {@link AuthoringTargets.excessKurtosis} when
   * nothing retreated.
   */
  readonly drawnExcessKurtosis?: number;
  /** Retreats the brief took from that draw. Absent on a hand-authored asset. */
  readonly retreats?: number;
  /**
   * The family's floor, present only when the rhythm drawn could not reach it
   * and the target was clamped *below* the band the archetype declares.
   */
  readonly clampedFrom?: number;
}

/**
 * An asset that has been through registration, with the evidence it produced.
 *
 * Registration is not repeated at startup. It is a deliberate act that produces
 * a lattice and a record of how that lattice was chosen, and the record is what
 * makes the choice auditable later. `catalogue.stat.test.ts` recalibrates every
 * asset here from different streams and fails if the recorded numbers do not
 * reproduce.
 */
export interface RegisteredAsset {
  readonly definition: AssetDefinition;
  readonly instrument: InstrumentSpec;
  readonly evidence: CalibrationEvidence;
  readonly authored: AuthoringTargets;
}

/**
 * Keyring label under which an asset's registration streams were derived.
 *
 * PH-10.1 §5.1: the analytic gate's structure term has no closed form and is
 * estimated by simulation, so the personality solve is exact only with respect
 * to the stream that drove it. Recording the label is what makes a registered
 * asset's tail weight reproducible rather than merely plausible.
 */
export function registrationKeyLabel(id: string): string {
  return `registration-${id}`;
}

/**
 * A compiled entry whose every number a run produced (PH-26.3).
 *
 * The five hand-authored assets were recorded by a `registered` helper that
 * fixed the calibration span and replicate count to the module defaults; it
 * went with them (PH-26.3). The thirty are produced by
 * `tools/sim/src/buildCatalogue.ts`, which calibrates each at the span its own
 * dispersion fit needs and records exactly that, so this takes the evidence
 * whole rather than assuming any of it.
 */
export function recorded(
  definition: AssetDefinition,
  authored: AuthoringTargets,
  lattice: { readonly logQuantum: number; readonly displayPrecision: number },
  evidence: CalibrationEvidence,
): RegisteredAsset {
  return {
    definition,
    authored,
    instrument: {
      id: definition.id,
      family: definition.family,
      logQuantum: lattice.logQuantum,
      displayPrecision: lattice.displayPrecision,
      referencePrice: definition.referencePrice,
    },
    evidence,
  };
}

/**
 * The asset catalogue: thirty assets, every number produced by a run.
 *
 * **PH-26.3.** The Human Owner asked for a library of thirty predefined OTC
 * assets — eight currency pairs, eight equities, six crypto pairs and eight
 * invented thematic indices — replacing the five hand-authored assets PH-4
 * built and PH-10 and PH-24.17 re-authored. Each asset's personality was drawn
 * from its **seat** (`seats.ts`) under a stream seeded by its own id, authored,
 * calibrated at three replicates of a third of the span its dispersion fit
 * needs, and differentiated against everything before it, by
 * `tools/sim/src/buildCatalogue.ts`:
 *
 * GENERATED by tools/sim/src/buildCatalogue.ts — do not edit by hand.
 * Regenerate with: npm run catalogue:build -- --replicates 3
 * Keyring: MasterKeyring.forTesting(registrationKeyLabel(id)) per asset; the draw derives under asset label `<id>`, the authoring under `registration-<id>`. Run label: catalogue-of-thirty-ph35. Run time: 7.1 minutes.
 *
 * **PH-35 (2026-09-23)** regenerated all thirty again, at the level the Human
 * Owner set once they had watched PH-34's market: the average is the real
 * instrument's (`OTC_DISPERSION_FACTOR` 1.0, from 1.7) and the rungs above
 * normal are compressed, a stressed candle 1.6 times a normal one rather than
 * 2.3. Tick rates are untouched: they follow each asset's reference
 * dispersion, which did not move.
 *
 * **PH-34 (2026-09-22)** regenerated all thirty on the new market model —
 * regimes that last like a market's at levels above the real one, a floor
 * under calm, ticks that follow the regime — with each asset's tick rate fitted
 * to its character and its budget at OTC level (`OTC_DISPERSION_FACTOR`). Every
 * lattice below is the one PH-26.3 recorded, kept: a running market's prices
 * are integers on it (`buildCatalogue.ts`).
 *
 * Nothing below was typed. The evidence table the same run wrote is
 * `docs/evidence/PH-26-CATALOGUE-OF-THIRTY.md`, and `catalogue.stat.test.ts`
 * recalibrates a stratified sample of these at every gate.
 *
 * ## Decisions that are the Human Owner's
 *
 * Equities are declared in the existing `etf` family; no archetype and no
 * family was added; the five incumbents are gone. Their ids — `eurusd`,
 * `gbpjpy`, `btcusd`, `spx`, `xauusd` — are retired and never reused, because a
 * checkpoint written under an id must never be resumed by another personality
 * under that id (`packages/runtime/src/personality.ts` now refuses it, and the
 * ids make it impossible anyway).
 *
 * ## What the names mean
 *
 * Eight instruments carry the names of listed companies and twenty-two the
 * names of real currency and crypto pairs, at reference prices measured as the
 * August 2026 monthly average of each. The reference price is the origin of
 * the log lattice and nothing more: this market tracks nothing, and the `OTC`
 * suffix on every display name is the convention that says so. The eight
 * thematic indices are inventions of this product and open at 1,000 USDT.
 *
 * Every quantum below was derived, never chosen: the 1% quantile of that
 * asset's own 30-second continuous return distribution. The realised rate on
 * the published lattice is about half that — see `MEASURED_LATTICE_TIE_RATES`
 * — because a tie is an integer-price event and the calibration measures a
 * continuous proxy for it.
 */
export const ASSET_CATALOGUE: readonly RegisteredAsset[] = [
  recorded(
    {
      id: 'eurusd-otc',
      family: 'forex',
      displayName: 'EUR/USD OTC',
      referencePrice: 1.16,
      traits: {
        tempoMs: 1895.7352218660178,
        volatility: 0.00001294399783064381,
        clustering: 0.20745226358687413,
        burstiness: 0.5686004158406961,
        regimeSpread: 0.9722267597484684,
        structureSpread: 1.0247632649957992,
        durationCoupling: 0.24849584307641298,
        cascadeDepth: 16,
        cascadeSpanMs: 147401773.69370702,
        cascadeSpacing: 1.967557681850178,
        regimeTempo: 1.914818009109728,
        arrivalMemoryMs: 387519.2406133858,
      },
    },
    {
      excessKurtosis: 51.74839887934475,
      tickRms: 0.000018132775651601625,
      drawnExcessKurtosis: 51.74839887934476,
      retreats: 0,
    },
    { logQuantum: 0.000004044597092506429, displayPrecision: 6 },
    {
      predictedExcessKurtosis: 47.63833473015517,
      logQuantum: 0.000004044597092506429,
      tieRate: 0.12880677095140936,
      realisedRefundRate: 0.03467100054173438,
      refundLatticeFactor: 12,
      medianSteps: 5.252380978932295,
      meanIntervalMs: 972.3127707827689,
      logVariancePerMs: 1.8569958847736624e-13,
      horizonMs: 30000,
      simulatedMs: 794004221,
      replicates: 3,
      horizons: 79398,
      volatilityScale: 1.3454319352915027,
    },
  ),
  recorded(
    {
      id: 'gbpusd-otc',
      family: 'forex',
      displayName: 'GBP/USD OTC',
      referencePrice: 1.35,
      traits: {
        tempoMs: 2082.4786702743922,
        volatility: 0.000011667615805976568,
        clustering: 0.2887860619870236,
        burstiness: 0.6361004973160823,
        regimeSpread: 1.0766293230364432,
        structureSpread: 0.9320257959606826,
        durationCoupling: 0.28671737458600555,
        cascadeDepth: 11,
        cascadeSpanMs: 90061553.05699967,
        cascadeSpacing: 2.6549445988340765,
        regimeTempo: 1.2422406366910805,
        arrivalMemoryMs: 204943.36773474203,
      },
    },
    {
      excessKurtosis: 72.67489029278549,
      tickRms: 0.000018126540960343166,
      drawnExcessKurtosis: 72.67489029278565,
      retreats: 0,
    },
    { logQuantum: 0.000004071035260851775, displayPrecision: 6 },
    {
      predictedExcessKurtosis: 70.22395148965745,
      logQuantum: 0.000004071035260851775,
      tieRate: 0.14748624080143466,
      realisedRefundRate: 0.03858815685293995,
      refundLatticeFactor: 16,
      medianSteps: 4.884858376681311,
      meanIntervalMs: 915.3460314944584,
      logVariancePerMs: 2.3778292181069957e-13,
      horizonMs: 30000,
      simulatedMs: 485131566,
      replicates: 3,
      horizons: 48513,
      volatilityScale: 1.2258821918482588,
    },
  ),
  recorded(
    {
      id: 'usdjpy-otc',
      family: 'forex',
      displayName: 'USD/JPY OTC',
      referencePrice: 159,
      traits: {
        tempoMs: 1866.8137599886343,
        volatility: 0.000011763963939781092,
        clustering: 0.24223116075388823,
        burstiness: 0.6039380190116258,
        regimeSpread: 1.06978151041035,
        structureSpread: 0.9284707356627397,
        durationCoupling: 0.2246043783756686,
        cascadeDepth: 14,
        cascadeSpanMs: 124987835.064402,
        cascadeSpacing: 2.3813665784744615,
        regimeTempo: 1.5299139831411468,
        arrivalMemoryMs: 159671.75030461754,
      },
    },
    {
      excessKurtosis: 63.38880622682393,
      tickRms: 0.000017534564071117013,
      drawnExcessKurtosis: 63.3888062268239,
      retreats: 0,
    },
    { logQuantum: 0.000004721767724047701, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 64.03200510905147,
      logQuantum: 0.000004721767724047701,
      tieRate: 0.13682678311499272,
      realisedRefundRate: 0.04317206317456349,
      refundLatticeFactor: 16,
      medianSteps: 5.139317761981169,
      meanIntervalMs: 828.519691153584,
      logVariancePerMs: 3.477366255144032e-13,
      horizonMs: 30000,
      simulatedMs: 673267805,
      replicates: 3,
      horizons: 67326,
      volatilityScale: 1.0283183996948033,
    },
  ),
  recorded(
    {
      id: 'audusd-otc',
      family: 'forex',
      displayName: 'AUD/USD OTC',
      referencePrice: 0.71,
      traits: {
        tempoMs: 2002.4626440672587,
        volatility: 0.000013422317993137647,
        clustering: 0.24664014680079832,
        burstiness: 0.6350395009829765,
        regimeSpread: 1.1484795808642667,
        structureSpread: 1.1185192758125486,
        durationCoupling: 0.18459049348536957,
        cascadeDepth: 13,
        cascadeSpanMs: 103272337.29755306,
        cascadeSpacing: 2.5162219504164516,
        regimeTempo: 1.4421240027053064,
        arrivalMemoryMs: 187037.1234118007,
      },
    },
    {
      excessKurtosis: 70.86598208875384,
      tickRms: 0.000019702838717011636,
      drawnExcessKurtosis: 70.86598208875381,
      retreats: 0,
    },
    { logQuantum: 0.000005788490926074027, displayPrecision: 6 },
    {
      predictedExcessKurtosis: 68.50438511630325,
      logQuantum: 0.000005788490926074027,
      tieRate: 0.14677596217800068,
      realisedRefundRate: 0.04400550068758594,
      refundLatticeFactor: 16,
      medianSteps: 4.712585926738946,
      meanIntervalMs: 786.1937410934478,
      logVariancePerMs: 4.326131687242797e-13,
      horizonMs: 30000,
      simulatedMs: 556293657,
      replicates: 3,
      horizons: 55629,
      volatilityScale: 1.064615900524013,
    },
  ),
  recorded(
    {
      id: 'usdchf-otc',
      family: 'forex',
      displayName: 'USD/CHF OTC',
      referencePrice: 0.81,
      traits: {
        tempoMs: 1884.7566011326496,
        volatility: 0.000008716720831203665,
        clustering: 0.2341128596145195,
        burstiness: 0.5256126291454096,
        regimeSpread: 0.9111136917379372,
        structureSpread: 0.981986405115825,
        durationCoupling: 0.26179931847852767,
        cascadeDepth: 13,
        cascadeSpanMs: 145831092.740785,
        cascadeSpacing: 2.2123092553896457,
        regimeTempo: 2.135877100162636,
        arrivalMemoryMs: 328284.42242269206,
      },
    },
    {
      excessKurtosis: 46.675647159011405,
      tickRms: 0.00001233055311898408,
      drawnExcessKurtosis: 46.67564715901146,
      retreats: 0,
    },
    { logQuantum: 0.000002936020835690536, displayPrecision: 6 },
    {
      predictedExcessKurtosis: 47.221538614276554,
      logQuantum: 0.000002936020835690536,
      tieRate: 0.11183674508605765,
      realisedRefundRate: 0.041630203775471934,
      refundLatticeFactor: 12,
      medianSteps: 6.237347800594157,
      meanIntervalMs: 1043.640703232738,
      logVariancePerMs: 1.400462962962963e-13,
      horizonMs: 30000,
      simulatedMs: 785543487,
      replicates: 3,
      horizons: 78552,
      volatilityScale: 1.0170264425207143,
    },
  ),
  recorded(
    {
      id: 'eurgbp-otc',
      family: 'forex',
      displayName: 'EUR/GBP OTC',
      referencePrice: 0.856,
      traits: {
        tempoMs: 2008.5591232165407,
        volatility: 0.00000924562746507911,
        clustering: 0.217612950426122,
        burstiness: 0.5468214169547922,
        regimeSpread: 1.0262965385532676,
        structureSpread: 1.1322742596486342,
        durationCoupling: 0.30484514889319614,
        cascadeDepth: 15,
        cascadeSpanMs: 109956936.0711137,
        cascadeSpacing: 2.092075364038772,
        regimeTempo: 1.762717737243383,
        arrivalMemoryMs: 274285.1737644539,
      },
    },
    {
      excessKurtosis: 60.29352793041002,
      tickRms: 0.000013081030253293511,
      drawnExcessKurtosis: 60.293527930410214,
      retreats: 0,
    },
    { logQuantum: 0.000002928561409753681, displayPrecision: 6 },
    {
      predictedExcessKurtosis: 59.25927417188693,
      logQuantum: 0.000002928561409753681,
      tieRate: 0.12105556399736615,
      realisedRefundRate: 0.03912989123640455,
      refundLatticeFactor: 12,
      medianSteps: 5.587099741803062,
      meanIntervalMs: 1096.8997415325202,
      logVariancePerMs: 1.1574074074074073e-13,
      horizonMs: 30000,
      simulatedMs: 592301363,
      replicates: 3,
      horizons: 59229,
      volatilityScale: 1.1588738154434084,
    },
  ),
  recorded(
    {
      id: 'gbpjpy-otc',
      family: 'forex',
      displayName: 'GBP/JPY OTC',
      referencePrice: 215,
      traits: {
        tempoMs: 1135.4832755397783,
        volatility: 0.00003888849808872357,
        clustering: 0.3956324542136621,
        burstiness: 0.6857773283992225,
        regimeSpread: 1.2954382195731176,
        structureSpread: 0.8730192594119726,
        durationCoupling: 0.3040141092050166,
        cascadeDepth: 6,
        cascadeSpanMs: 42813798.23860636,
        cascadeSpacing: 4.105971023360371,
        regimeTempo: 0.41490023799441395,
        arrivalMemoryMs: 26502.30308471578,
      },
    },
    {
      excessKurtosis: 41.889085884970505,
      tickRms: 0.00006015701657323348,
      drawnExcessKurtosis: 46.543428761078246,
      retreats: 1,
      clampedFrom: 120,
    },
    { logQuantum: 0.000015096056539817884, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 42.97612291484486,
      logQuantum: 0.000015096056539817884,
      tieRate: 0.1548263888888889,
      realisedRefundRate: 0.041630203775471934,
      refundLatticeFactor: 16,
      medianSteps: 5.2352726252236055,
      meanIntervalMs: 420.584290884663,
      logVariancePerMs: 5.94457304526749e-12,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 1.2167254323744194,
    },
  ),
  recorded(
    {
      id: 'eurjpy-otc',
      family: 'forex',
      displayName: 'EUR/JPY OTC',
      referencePrice: 184,
      traits: {
        tempoMs: 1153.0704609849868,
        volatility: 0.000022260839773593976,
        clustering: 0.3310967837042701,
        burstiness: 0.5730426507629183,
        regimeSpread: 1.1027899483714698,
        structureSpread: 1.0932902455256868,
        durationCoupling: 0.19290762141446954,
        cascadeDepth: 9,
        cascadeSpanMs: 23480861.93597185,
        cascadeSpacing: 3.063182343697715,
        regimeTempo: 0.795528385547744,
        arrivalMemoryMs: 62192.111810422,
      },
    },
    {
      excessKurtosis: 85.16937131721065,
      tickRms: 0.000035549601186492185,
      drawnExcessKurtosis: 85.1693713172107,
      retreats: 0,
    },
    { logQuantum: 0.000012146979134430585, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 85.20426060912509,
      logQuantum: 0.000012146979134430585,
      tieRate: 0.17180555555555554,
      realisedRefundRate: 0.047755969496187024,
      refundLatticeFactor: 16,
      medianSteps: 4.365401031233169,
      meanIntervalMs: 484.4260392452373,
      logVariancePerMs: 2.893518518518519e-12,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 0.9418926974262736,
    },
  ),
  recorded(
    {
      id: 'aapl-otc',
      family: 'etf',
      displayName: 'Apple OTC',
      referencePrice: 310,
      traits: {
        tempoMs: 897.9621236137972,
        volatility: 0.00002796927547239333,
        clustering: 0.25871776906996635,
        burstiness: 0.4500253687203627,
        regimeSpread: 0.9211425277666317,
        structureSpread: 1.2750974748992998,
        durationCoupling: 0.22740622265143204,
        cascadeDepth: 10,
        cascadeSpanMs: 141460958.02249637,
        cascadeSpacing: 2.701158375806777,
        regimeTempo: 1.7922310393918115,
        arrivalMemoryMs: 361629.04836906376,
      },
    },
    {
      excessKurtosis: 52.609489129326064,
      tickRms: 0.00003866969891901029,
      drawnExcessKurtosis: 52.60948912932613,
      retreats: 0,
    },
    { logQuantum: 0.000012790337130389883, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 50.426756563622504,
      logQuantum: 0.000012790337130389883,
      tieRate: 0.14017060367454068,
      realisedRefundRate: 0.035296078676501225,
      refundLatticeFactor: 16,
      medianSteps: 4.827938614883947,
      meanIntervalMs: 547.4276353111932,
      logVariancePerMs: 1.8518518518518517e-12,
      horizonMs: 30000,
      simulatedMs: 762003028,
      replicates: 3,
      horizons: 76200,
      volatilityScale: 1.2112115324423776,
    },
  ),
  recorded(
    {
      id: 'msft-otc',
      family: 'etf',
      displayName: 'Microsoft OTC',
      referencePrice: 495,
      traits: {
        tempoMs: 930.1198425174083,
        volatility: 0.00002251516437597768,
        clustering: 0.2646262897107131,
        burstiness: 0.4354440102342018,
        regimeSpread: 0.88014454831829,
        structureSpread: 1.3299855096211497,
        durationCoupling: 0.22699941339496393,
        cascadeDepth: 9,
        cascadeSpanMs: 138271972.1133019,
        cascadeSpacing: 3.374734408722801,
        regimeTempo: 2.191524457962109,
        arrivalMemoryMs: 413187.6913292819,
      },
    },
    {
      excessKurtosis: 47.07821613300916,
      tickRms: 0.000030531740982634954,
      drawnExcessKurtosis: 47.07821613300918,
      retreats: 0,
    },
    { logQuantum: 0.00001078704890296888, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 47.49970037372968,
      logQuantum: 0.00001078704890296888,
      tieRate: 0.12605899491145392,
      realisedRefundRate: 0.041296828770262944,
      refundLatticeFactor: 12,
      medianSteps: 5.421440592920555,
      meanIntervalMs: 582.1929238734851,
      logVariancePerMs: 1.417824074074074e-12,
      horizonMs: 30000,
      simulatedMs: 744825024,
      replicates: 3,
      horizons: 74481,
      volatilityScale: 1.0570480665642352,
    },
  ),
  recorded(
    {
      id: 'nvda-otc',
      family: 'etf',
      displayName: 'NVIDIA OTC',
      referencePrice: 220,
      traits: {
        tempoMs: 706.9173391731154,
        volatility: 0.00004060068765451161,
        clustering: 0.30418343827308203,
        burstiness: 0.5556645630966711,
        regimeSpread: 1.0789333294547927,
        structureSpread: 1.1334901140641112,
        durationCoupling: 0.3271398186252985,
        cascadeDepth: 9,
        cascadeSpanMs: 90771571.5269747,
        cascadeSpacing: 2.2118630750559207,
        regimeTempo: 1.3991846120552154,
        arrivalMemoryMs: 209182.25349751182,
      },
    },
    {
      excessKurtosis: 64.93191557134688,
      tickRms: 0.000060461539654526194,
      drawnExcessKurtosis: 64.9319155713468,
      retreats: 0,
    },
    { logQuantum: 0.00002122590797953285, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 62.298113275494245,
      logQuantum: 0.00002122590797953285,
      tieRate: 0.1434122796253119,
      realisedRefundRate: 0.03854648497728883,
      refundLatticeFactor: 16,
      medianSteps: 5.110542455676006,
      meanIntervalMs: 367.6468361870079,
      logVariancePerMs: 8.693415637860084e-12,
      horizonMs: 30000,
      simulatedMs: 488956199,
      replicates: 3,
      horizons: 48894,
      volatilityScale: 1.060435681539085,
    },
  ),
  recorded(
    {
      id: 'tsla-otc',
      family: 'etf',
      displayName: 'Tesla OTC',
      referencePrice: 340,
      traits: {
        tempoMs: 605.594781961031,
        volatility: 0.000055069277148817165,
        clustering: 0.2774940528502964,
        burstiness: 0.5331560550183579,
        regimeSpread: 1.092497857631795,
        structureSpread: 1.1711156567974987,
        durationCoupling: 0.3394507018308368,
        cascadeDepth: 10,
        cascadeSpanMs: 73679202.6143589,
        cascadeSpacing: 2.9400894077244906,
        regimeTempo: 1.4776272172358955,
        arrivalMemoryMs: 291156.03223236755,
      },
    },
    {
      excessKurtosis: 62.59199680470313,
      tickRms: 0.00007979833667052457,
      drawnExcessKurtosis: 62.59199680470315,
      retreats: 0,
    },
    { logQuantum: 0.00003976917497379534, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 61.19413754623062,
      logQuantum: 0.00003976917497379534,
      tieRate: 0.15627283493335348,
      realisedRefundRate: 0.04071342251114723,
      refundLatticeFactor: 16,
      medianSteps: 4.317764579287086,
      meanIntervalMs: 344.7999408660831,
      logVariancePerMs: 1.1574074074074077e-11,
      horizonMs: 30000,
      simulatedMs: 396885305,
      replicates: 3,
      horizons: 39687,
      volatilityScale: 1.2571527190279441,
    },
  ),
  recorded(
    {
      id: 'meta-otc',
      family: 'etf',
      displayName: 'Meta OTC',
      referencePrice: 575,
      traits: {
        tempoMs: 694.5950179216959,
        volatility: 0.00002828898072938953,
        clustering: 0.24312544235593664,
        burstiness: 0.4907503682434591,
        regimeSpread: 0.9339532575271764,
        structureSpread: 1.3929145448592113,
        durationCoupling: 0.283404261331114,
        cascadeDepth: 11,
        cascadeSpanMs: 117342208.15545748,
        cascadeSpacing: 2.5964503319129175,
        regimeTempo: 1.602801981459484,
        arrivalMemoryMs: 319090.2001480793,
      },
    },
    {
      excessKurtosis: 59.030045663566696,
      tickRms: 0.00003879655234512346,
      drawnExcessKurtosis: 59.03004566356671,
      retreats: 0,
    },
    { logQuantum: 0.0000179278887905132, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 60.386030795847105,
      logQuantum: 0.0000179278887905132,
      tieRate: 0.11114275317607226,
      realisedRefundRate: 0.040171688127682625,
      refundLatticeFactor: 12,
      medianSteps: 6.2420840937514015,
      meanIntervalMs: 408.04273683961367,
      logVariancePerMs: 5.6712962962962965e-12,
      horizonMs: 30000,
      simulatedMs: 632083362,
      replicates: 3,
      horizons: 63207,
      volatilityScale: 0.7986634388892839,
    },
  ),
  recorded(
    {
      id: 'amzn-otc',
      family: 'etf',
      displayName: 'Amazon OTC',
      referencePrice: 265,
      traits: {
        tempoMs: 805.6694094962725,
        volatility: 0.00003764587234444086,
        clustering: 0.2332254738582839,
        burstiness: 0.48700089136254265,
        regimeSpread: 0.9882636681569292,
        structureSpread: 1.258021665950809,
        durationCoupling: 0.2243972736963484,
        cascadeDepth: 12,
        cascadeSpanMs: 96813432.14325012,
        cascadeSpacing: 2.396246963589943,
        regimeTempo: 1.8793904654031315,
        arrivalMemoryMs: 293205.2527692481,
      },
    },
    {
      excessKurtosis: 53.674639298612846,
      tickRms: 0.00005172913560286648,
      drawnExcessKurtosis: 53.67463929861283,
      retreats: 0,
    },
    { logQuantum: 0.000021551653131290453, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 51.266991914630374,
      logQuantum: 0.000021551653131290453,
      tieRate: 0.14903449730579685,
      realisedRefundRate: 0.038504813101637704,
      refundLatticeFactor: 16,
      medianSteps: 4.4209408325334065,
      meanIntervalMs: 460.46518576597674,
      logVariancePerMs: 3.71656378600823e-12,
      horizonMs: 30000,
      simulatedMs: 521501688,
      replicates: 3,
      horizons: 52149,
      volatilityScale: 1.247767505427899,
    },
  ),
  recorded(
    {
      id: 'pbr-otc',
      family: 'etf',
      displayName: 'Petrobras OTC',
      referencePrice: 18.4,
      traits: {
        tempoMs: 807.5232685861457,
        volatility: 0.00003587201792442643,
        clustering: 0.2657024168634955,
        burstiness: 0.548236574687773,
        regimeSpread: 1.0432440002115073,
        structureSpread: 1.1159142395960095,
        durationCoupling: 0.3042779476014586,
        cascadeDepth: 11,
        cascadeSpanMs: 73822502.8797999,
        cascadeSpacing: 2.747893867733064,
        regimeTempo: 1.4909880134451858,
        arrivalMemoryMs: 182497.64544208025,
      },
    },
    {
      excessKurtosis: 57.86536165956777,
      tickRms: 0.00005220362448028025,
      drawnExcessKurtosis: 57.86536165956785,
      retreats: 0,
    },
    { logQuantum: 0.000020977812970554404, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 60.09688345528127,
      logQuantum: 0.000020977812970554404,
      tieRate: 0.129812649314724,
      realisedRefundRate: 0.04529732883277077,
      refundLatticeFactor: 12,
      medianSteps: 5.209305266042103,
      meanIntervalMs: 430.8131721459123,
      logVariancePerMs: 4.6424897119341586e-12,
      horizonMs: 30000,
      simulatedMs: 397657216,
      replicates: 3,
      horizons: 39765,
      volatilityScale: 1.1584321376559163,
    },
  ),
  recorded(
    {
      id: 'nu-otc',
      family: 'etf',
      displayName: 'Nubank OTC',
      referencePrice: 14.4,
      traits: {
        tempoMs: 596.7287966396777,
        volatility: 0.00004155232391847729,
        clustering: 0.3238381497591004,
        burstiness: 0.5082893571475382,
        regimeSpread: 1.0378888054750472,
        structureSpread: 1.1076478837551782,
        durationCoupling: 0.29980194155716217,
        cascadeDepth: 8,
        cascadeSpanMs: 117911966.74169706,
        cascadeSpacing: 3.228004367598419,
        regimeTempo: 1.4408770836888893,
        arrivalMemoryMs: 190952.96352981715,
      },
    },
    {
      excessKurtosis: 56.48171645086947,
      tickRms: 0.00006192155411578764,
      drawnExcessKurtosis: 56.48171645086944,
      retreats: 0,
    },
    { logQuantum: 0.000027620254336536803, displayPrecision: 4 },
    {
      predictedExcessKurtosis: 56.67683388343987,
      logQuantum: 0.000027620254336536803,
      tieRate: 0.15020546974635113,
      realisedRefundRate: 0.04713089136142018,
      refundLatticeFactor: 16,
      medianSteps: 4.873164230261816,
      meanIntervalMs: 332.1162234081028,
      logVariancePerMs: 1.3168724279835393e-11,
      horizonMs: 30000,
      simulatedMs: 635152461,
      replicates: 3,
      horizons: 63513,
      volatilityScale: 0.9294253318693751,
    },
  ),
  recorded(
    {
      id: 'btcusdt-otc',
      family: 'crypto',
      displayName: 'BTC/USDT OTC',
      referencePrice: 70_000,
      traits: {
        tempoMs: 1013.5114034693488,
        volatility: 0.00005069786532876306,
        clustering: 0.24110196844857074,
        burstiness: 0.7220786749171393,
        regimeSpread: 1.2713434035603812,
        structureSpread: 0.9207727097424919,
        durationCoupling: 0.22488694928580782,
        cascadeDepth: 17,
        cascadeSpanMs: 128646905.7664875,
        cascadeSpacing: 1.9013373006643652,
        regimeTempo: 0.48747317327202216,
        arrivalMemoryMs: 29024.618373211953,
      },
    },
    {
      excessKurtosis: 116.92560128107323,
      tickRms: 0.0000819543412372622,
      drawnExcessKurtosis: 116.92560128107327,
      retreats: 0,
    },
    { logQuantum: 0.00002400941219697859, displayPrecision: 0 },
    {
      predictedExcessKurtosis: 112.21505716005305,
      logQuantum: 0.00002400941219697859,
      tieRate: 0.14863558306997418,
      realisedRefundRate: 0.03946326624161354,
      refundLatticeFactor: 16,
      medianSteps: 5.2311306663731765,
      meanIntervalMs: 325.5043834103045,
      logVariancePerMs: 1.486625514403293e-11,
      horizonMs: 30000,
      simulatedMs: 692978000,
      replicates: 3,
      horizons: 69297,
      volatilityScale: 1.1754331022720943,
    },
  ),
  recorded(
    {
      id: 'ethusdt-otc',
      family: 'crypto',
      displayName: 'ETH/USDT OTC',
      referencePrice: 2_100,
      traits: {
        tempoMs: 946.706740098577,
        volatility: 0.00006542846127652534,
        clustering: 0.2676712901475514,
        burstiness: 0.7972777987110796,
        regimeSpread: 1.4209645775934465,
        structureSpread: 1.0339365321308716,
        durationCoupling: 0.2741459614922707,
        cascadeDepth: 15,
        cascadeSpanMs: 103871390.15977749,
        cascadeSpacing: 2.123307134860964,
        regimeTempo: 0.3055371754370963,
        arrivalMemoryMs: 19950.315719723258,
      },
    },
    {
      excessKurtosis: 152.58245083728153,
      tickRms: 0.00010994048429398249,
      drawnExcessKurtosis: 152.58245083728178,
      retreats: 0,
    },
    { logQuantum: 0.000037195782215006836, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 152.08516419468344,
      logQuantum: 0.000037195782215006836,
      tieRate: 0.16761394101876675,
      realisedRefundRate: 0.04363045380672584,
      refundLatticeFactor: 16,
      medianSteps: 4.535711373154846,
      meanIntervalMs: 285.8250077902971,
      logVariancePerMs: 2.4897119341563784e-11,
      horizonMs: 30000,
      simulatedMs: 559520555,
      replicates: 3,
      horizons: 55950,
      volatilityScale: 1.2995807791385714,
    },
  ),
  recorded(
    {
      id: 'bnbusdt-otc',
      family: 'crypto',
      displayName: 'BNB/USDT OTC',
      referencePrice: 650,
      traits: {
        tempoMs: 874.378287970934,
        volatility: 0.00006226660663530737,
        clustering: 0.260922572410457,
        burstiness: 0.7469353321375733,
        regimeSpread: 1.3099848481733545,
        structureSpread: 1.0869161042797584,
        durationCoupling: 0.3402085344931937,
        cascadeDepth: 15,
        cascadeSpanMs: 88110341.17071961,
        cascadeSpacing: 1.9999132967374997,
        regimeTempo: 0.40444878060427125,
        arrivalMemoryMs: 21180.543355418667,
      },
    },
    {
      excessKurtosis: 137.02364768508008,
      tickRms: 0.00010204350462120417,
      drawnExcessKurtosis: 137.02364768508,
      retreats: 0,
    },
    { logQuantum: 0.000024697121279992967, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 138.35189415098773,
      logQuantum: 0.000024697121279992967,
      tieRate: 0.13428150021070376,
      realisedRefundRate: 0.03650456307038379,
      refundLatticeFactor: 16,
      medianSteps: 5.836459254678787,
      meanIntervalMs: 303.7993967380671,
      logVariancePerMs: 2.0576131687242805e-11,
      horizonMs: 30000,
      simulatedMs: 474621038,
      replicates: 3,
      horizons: 47460,
      volatilityScale: 1.2956136455398284,
    },
  ),
  recorded(
    {
      id: 'solusdt-otc',
      family: 'crypto',
      displayName: 'SOL/USDT OTC',
      referencePrice: 85,
      traits: {
        tempoMs: 695.8236042358043,
        volatility: 0.00009372632016340809,
        clustering: 0.38884881855643594,
        burstiness: 0.8171079017304319,
        regimeSpread: 1.385665185565065,
        structureSpread: 0.9474363420652783,
        durationCoupling: 0.47908466213582923,
        cascadeDepth: 8,
        cascadeSpanMs: 14243617.084324839,
        cascadeSpacing: 3.265774339795158,
        regimeTempo: 0.4904738399549584,
        arrivalMemoryMs: 27435.656370368593,
      },
    },
    {
      excessKurtosis: 105.96957585769051,
      tickRms: 0.00016461515915907108,
      drawnExcessKurtosis: 117.7439731752116,
      retreats: 1,
      clampedFrom: 140,
    },
    { logQuantum: 0.000045937577312699555, displayPrecision: 3 },
    {
      predictedExcessKurtosis: 100.56614854895813,
      logQuantum: 0.000045937577312699555,
      tieRate: 0.1407986111111111,
      realisedRefundRate: 0.03962995374421803,
      refundLatticeFactor: 16,
      medianSteps: 5.469509617617771,
      meanIntervalMs: 246.231503781962,
      logVariancePerMs: 4.4765946502057606e-11,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 1.561586186410252,
    },
  ),
  recorded(
    {
      id: 'xrpusdt-otc',
      family: 'crypto',
      displayName: 'XRP/USDT OTC',
      referencePrice: 1.2,
      traits: {
        tempoMs: 741.9044810742082,
        volatility: 0.00006573880153480392,
        clustering: 0.36717551504196944,
        burstiness: 0.7468900313314695,
        regimeSpread: 1.277945624547593,
        structureSpread: 1.1419700245951614,
        durationCoupling: 0.3428495605461378,
        cascadeDepth: 9,
        cascadeSpanMs: 16580828.760966431,
        cascadeSpacing: 2.706348618200529,
        regimeTempo: 0.522601052092699,
        arrivalMemoryMs: 43540.18230900274,
      },
    },
    {
      excessKurtosis: 136.31636402692442,
      tickRms: 0.00011614205609720277,
      drawnExcessKurtosis: 136.31636402692394,
      retreats: 0,
    },
    { logQuantum: 0.00003387093432005904, displayPrecision: 5 },
    {
      predictedExcessKurtosis: 141.991928586435,
      logQuantum: 0.00003387093432005904,
      tieRate: 0.16701388888888888,
      realisedRefundRate: 0.04063007875984498,
      refundLatticeFactor: 16,
      medianSteps: 4.987207992320826,
      meanIntervalMs: 255.9380440349699,
      logVariancePerMs: 3.6123971193415635e-11,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 1.19403690242667,
    },
  ),
  recorded(
    {
      id: 'dogeusdt-otc',
      family: 'crypto',
      displayName: 'DOGE/USDT OTC',
      referencePrice: 0.078,
      traits: {
        tempoMs: 637.9921969658825,
        volatility: 0.00012898527661536698,
        clustering: 0.39093603679496713,
        burstiness: 0.8698176950362948,
        regimeSpread: 1.4499198385651457,
        structureSpread: 0.8378234649824825,
        durationCoupling: 0.6073960251478318,
        cascadeDepth: 7,
        cascadeSpanMs: 6370365.419998091,
        cascadeSpacing: 3.891954861930036,
        regimeTempo: 0.35090506158931006,
        arrivalMemoryMs: 15589.486342561086,
      },
    },
    {
      excessKurtosis: 64.98459113495255,
      tickRms: 0.00021218754174649092,
      drawnExcessKurtosis: 72.20510126105846,
      retreats: 1,
      clampedFrom: 150,
    },
    { logQuantum: 0.00007449361347735962, displayPrecision: 6 },
    {
      predictedExcessKurtosis: 64.52662320424936,
      logQuantum: 0.00007449361347735962,
      tieRate: 0.1506597222222222,
      realisedRefundRate: 0.04088011001375172,
      refundLatticeFactor: 16,
      medianSteps: 4.6533378315458425,
      meanIntervalMs: 235.16423935800162,
      logVariancePerMs: 5.601851851851853e-11,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 1.850534008704821,
    },
  ),
  recorded(
    {
      id: 'mmx-idx-otc',
      family: 'crypto',
      displayName: 'MMX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 677.5526551051574,
        volatility: 0.00011690061691758818,
        clustering: 0.36912953127575243,
        burstiness: 0.8416366994314232,
        regimeSpread: 1.4060355669840057,
        structureSpread: 1.1422891332683482,
        durationCoupling: 0.5091753057338805,
        cascadeDepth: 9,
        cascadeSpanMs: 16074586.626181249,
        cascadeSpacing: 2.6575030907913995,
        regimeTempo: 0.5739372503145908,
        arrivalMemoryMs: 41334.264992063465,
      },
    },
    {
      excessKurtosis: 149.86300161239083,
      tickRms: 0.00020771157871136175,
      drawnExcessKurtosis: 149.8630016123912,
      retreats: 0,
    },
    { logQuantum: 0.0000536308458831654, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 151.20357979929253,
      logQuantum: 0.0000536308458831654,
      tieRate: 0.16284722222222223,
      realisedRefundRate: 0.03771304746426637,
      refundLatticeFactor: 16,
      medianSteps: 4.776275495935608,
      meanIntervalMs: 238.18292890019032,
      logVariancePerMs: 4.9434156378600824e-11,
      horizonMs: 30000,
      simulatedMs: 288000000,
      replicates: 3,
      horizons: 28800,
      volatilityScale: 1.8984627517123276,
    },
  ),
  recorded(
    {
      id: 'cgx-idx-otc',
      family: 'crypto',
      displayName: 'CGX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 1003.7600745309244,
        volatility: 0.0000658795425531432,
        clustering: 0.24210697859248914,
        burstiness: 0.7841519450237221,
        regimeSpread: 1.3732092963592206,
        structureSpread: 1.0861910600969085,
        durationCoupling: 0.2806660978111063,
        cascadeDepth: 16,
        cascadeSpanMs: 127507297.07389174,
        cascadeSpacing: 1.8872042037933296,
        regimeTempo: 0.48066099995659256,
        arrivalMemoryMs: 25461.206040510147,
      },
    },
    {
      excessKurtosis: 120.36835157751139,
      tickRms: 0.00010391003999623657,
      drawnExcessKurtosis: 120.36835157751123,
      retreats: 0,
    },
    { logQuantum: 0.000028298498715901247, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 121.194080092652,
      logQuantum: 0.000028298498715901247,
      tieRate: 0.13296060103083776,
      realisedRefundRate: 0.037046297453848395,
      refundLatticeFactor: 16,
      medianSteps: 5.730909149402703,
      meanIntervalMs: 308.9993877051555,
      logVariancePerMs: 1.8569958847736625e-11,
      horizonMs: 30000,
      simulatedMs: 686839307,
      replicates: 3,
      horizons: 68682,
      volatilityScale: 1.371055248597759,
    },
  ),
  recorded(
    {
      id: 'aix-idx-otc',
      family: 'index',
      displayName: 'AIX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 730.3118065814398,
        volatility: 0.00003558998207739721,
        clustering: 0.2435570636500088,
        burstiness: 0.527661012773273,
        regimeSpread: 0.7807929928078016,
        structureSpread: 1.431616973622877,
        durationCoupling: 0.3046785755969861,
        cascadeDepth: 10,
        cascadeSpanMs: 162438862.37785017,
        cascadeSpacing: 3.175214092603512,
        regimeTempo: 2.7327022082053456,
        arrivalMemoryMs: 589114.5526163417,
      },
    },
    {
      excessKurtosis: 48.58183828605254,
      tickRms: 0.000047474862682114167,
      drawnExcessKurtosis: 48.58183828605249,
      retreats: 0,
    },
    { logQuantum: 0.000019374532515471326, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 47.88123198100068,
      logQuantum: 0.000019374532515471326,
      tieRate: 0.1102882351596608,
      realisedRefundRate: 0.03912989123640455,
      refundLatticeFactor: 12,
      medianSteps: 6.066867753511305,
      meanIntervalMs: 423.13031144988605,
      logVariancePerMs: 5.1440329218107e-12,
      horizonMs: 30000,
      simulatedMs: 875004006,
      replicates: 3,
      horizons: 87498,
      volatilityScale: 1.0137394828760302,
    },
  ),
  recorded(
    {
      id: 'tcx-idx-otc',
      family: 'index',
      displayName: 'TCX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 822.8173928890436,
        volatility: 0.000030626374519780675,
        clustering: 0.27939408169634083,
        burstiness: 0.4399061999364536,
        regimeSpread: 0.8874283155193491,
        structureSpread: 1.2153618173375587,
        durationCoupling: 0.21296312294862646,
        cascadeDepth: 8,
        cascadeSpanMs: 139235927.3681038,
        cascadeSpacing: 3.7179380035729364,
        regimeTempo: 2.244307444393512,
        arrivalMemoryMs: 317523.17676743085,
      },
    },
    {
      excessKurtosis: 38.82822616238584,
      tickRms: 0.00004136842774315921,
      drawnExcessKurtosis: 38.828226162385924,
      retreats: 0,
    },
    { logQuantum: 0.000016245503430818698, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 37.903817774749925,
      logQuantum: 0.000016245503430818698,
      tieRate: 0.15074666666666667,
      realisedRefundRate: 0.043130391298912364,
      refundLatticeFactor: 16,
      medianSteps: 4.384695024347381,
      meanIntervalMs: 502.48480454467904,
      logVariancePerMs: 2.5205761316872434e-12,
      horizonMs: 30000,
      simulatedMs: 750017529,
      replicates: 3,
      horizons: 75000,
      volatilityScale: 1.154271917328592,
    },
  ),
  recorded(
    {
      id: 'scx-idx-otc',
      family: 'index',
      displayName: 'SCX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 698.0459109943511,
        volatility: 0.000042349295554073156,
        clustering: 0.2976182197672109,
        burstiness: 0.5506165404927515,
        regimeSpread: 0.9258311359115483,
        structureSpread: 1.2831754502075932,
        durationCoupling: 0.2942750830327222,
        cascadeDepth: 7,
        cascadeSpanMs: 137820171.82658166,
        cascadeSpacing: 3.7897671146367884,
        regimeTempo: 1.9744098500564375,
        arrivalMemoryMs: 589531.9701971862,
      },
    },
    {
      excessKurtosis: 39.59347045607202,
      tickRms: 0.00005699708930999157,
      drawnExcessKurtosis: 39.593470456072,
      retreats: 0,
    },
    { logQuantum: 0.00002686802294642805, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 39.84335864224093,
      logQuantum: 0.00002686802294642805,
      tieRate: 0.13806945230205556,
      realisedRefundRate: 0.04404717256323707,
      refundLatticeFactor: 16,
      medianSteps: 4.8647794457083595,
      meanIntervalMs: 386.67631366357347,
      logVariancePerMs: 7.407407407407408e-12,
      horizonMs: 30000,
      simulatedMs: 742391326,
      replicates: 3,
      horizons: 74238,
      volatilityScale: 1.0615229495456455,
    },
  ),
  recorded(
    {
      id: 'gmx-idx-otc',
      family: 'etf',
      displayName: 'GMX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 851.4771247653895,
        volatility: 0.000044743153091808336,
        clustering: 0.3142004926565566,
        burstiness: 0.550559179813238,
        regimeSpread: 0.8931146109392845,
        structureSpread: 1.3116939989623744,
        durationCoupling: 0.23209911711567402,
        cascadeDepth: 8,
        cascadeSpanMs: 79501844.52784836,
        cascadeSpacing: 2.2795813499878594,
        regimeTempo: 1.3785620633030269,
        arrivalMemoryMs: 183961.9829105928,
      },
    },
    {
      excessKurtosis: 65.46361797586053,
      tickRms: 0.00006520453297651567,
      drawnExcessKurtosis: 65.4636179758605,
      retreats: 0,
    },
    { logQuantum: 0.000022525806716134888, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 64.75824331649342,
      logQuantum: 0.000022525806716134888,
      tieRate: 0.150379451255108,
      realisedRefundRate: 0.03962995374421802,
      refundLatticeFactor: 16,
      medianSteps: 4.615281864895024,
      meanIntervalMs: 408.7618080398902,
      logVariancePerMs: 6.224279835390947e-12,
      horizonMs: 30000,
      simulatedMs: 428249936,
      replicates: 3,
      horizons: 42825,
      volatilityScale: 1.2962713402493364,
    },
  ),
  recorded(
    {
      id: 'evx-idx-otc',
      family: 'etf',
      displayName: 'EVX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 554.6939263350308,
        volatility: 0.00004845625805013889,
        clustering: 0.24452072136357056,
        burstiness: 0.47648412126411704,
        regimeSpread: 1.0966355945649306,
        structureSpread: 1.257184825677404,
        durationCoupling: 0.3304014623744861,
        cascadeDepth: 12,
        cascadeSpanMs: 137194201.65232572,
        cascadeSpacing: 2.9143528612443057,
        regimeTempo: 2.086904624664351,
        arrivalMemoryMs: 340256.0740542225,
      },
    },
    {
      excessKurtosis: 65.81976523612991,
      tickRms: 0.00006865461233590313,
      drawnExcessKurtosis: 65.81976523612995,
      retreats: 0,
    },
    { logQuantum: 0.000040857421337362215, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 65.14283249289127,
      logQuantum: 0.000040857421337362215,
      tieRate: 0.1517070596354484,
      realisedRefundRate: 0.04496395382756178,
      refundLatticeFactor: 16,
      medianSteps: 4.334613063833167,
      meanIntervalMs: 344.84357298942587,
      logVariancePerMs: 1.1574074074074069e-11,
      horizonMs: 30000,
      simulatedMs: 739019433,
      replicates: 3,
      horizons: 73899,
      volatilityScale: 1.0815931280403552,
    },
  ),
  recorded(
    {
      id: 'brx-idx-otc',
      family: 'etf',
      displayName: 'BRX/USDT OTC',
      referencePrice: 1_000,
      traits: {
        tempoMs: 734.1166216307187,
        volatility: 0.00003757312200033783,
        clustering: 0.23399472493374923,
        burstiness: 0.4299559829462449,
        regimeSpread: 0.9588801685103342,
        structureSpread: 1.3794547334064147,
        durationCoupling: 0.21804668624743972,
        cascadeDepth: 10,
        cascadeSpanMs: 86881609.66184996,
        cascadeSpacing: 3.3673831457402876,
        regimeTempo: 1.5207090725397223,
        arrivalMemoryMs: 242114.1168669156,
      },
    },
    {
      excessKurtosis: 42.55240737016252,
      tickRms: 0.000049049233276107474,
      drawnExcessKurtosis: 42.552407370162435,
      retreats: 0,
    },
    { logQuantum: 0.00002051979260534711, displayPrecision: 2 },
    {
      predictedExcessKurtosis: 42.307330702805274,
      logQuantum: 0.00002051979260534711,
      tieRate: 0.11905982905982906,
      realisedRefundRate: 0.03625453181647706,
      refundLatticeFactor: 12,
      medianSteps: 5.324180464717456,
      meanIntervalMs: 458.3021531609638,
      logVariancePerMs: 3.71656378600823e-12,
      horizonMs: 30000,
      simulatedMs: 468002271,
      replicates: 3,
      horizons: 46800,
      volatilityScale: 1.183125113822476,
    },
  ),
];

export function assetById(id: string): RegisteredAsset {
  const found = ASSET_CATALOGUE.find((asset) => asset.definition.id === id);
  if (found === undefined) {
    const known = ASSET_CATALOGUE.map((asset) => asset.definition.id).join(', ');
    throw new RangeError(`Unknown asset ${id}. The catalogue holds: ${known}.`);
  }
  return found;
}

/** The engine configuration for a registered asset. */
export function configFor(asset: RegisteredAsset): MarketEngineConfig {
  return { ...personalityConfig(asset.definition.traits), instrument: asset.instrument };
}
