export {
  AUTHORING_ATTEMPTS,
  AUTHORING_RETREAT,
  requestFromBrief,
  type AssetBrief,
} from './brief.js';
export { PoissonArrivalModel } from './arrival.js';
export {
  createMarketEngine,
  defaultConfigFor,
  DEFAULT_ENGINE_CONFIG,
  ENGINE_MODEL,
  ENGINE_STREAM_PURPOSES,
  type CreateEngineOptions,
  type MarketEngineConfig,
} from './factory.js';
export {
  assertHawkesConfig,
  DEFAULT_DURATION_COUPLING,
  DEFAULT_HAWKES,
  DurationCouplingModulator,
  HawkesArrivalModel,
  type ActivitySource,
  type HawkesConfig,
  type HawkesSnapshot,
} from './hawkes.js';
export {
  assertCascadeConfig,
  cascadeTypicalProduct,
  CascadeMagnitudeModel,
  DEFAULT_CASCADE,
  MAX_CASCADE_COMPONENTS,
  VolatilityCascade,
  type CascadeConfig,
  type CascadeSnapshot,
} from './cascade.js';
export {
  logUnitsPerRelativeMove,
  MarketEngine,
  type EngineSnapshot,
  type EngineStart,
  type EngineStreams,
  type MarketEngineOptions,
} from './engine.js';
export type { ArrivalModel, MagnitudeContext, MagnitudeModel } from './magnitude.js';
export { ModulatedMagnitudeModel, type Modulator } from './modulator.js';
export {
  assertVolatilityFloorConfig,
  VolatilityFloorModulator,
  type FloorSources,
  type VolatilityFloorConfig,
} from './floor.js';
export {
  assertRegimeConfig,
  DEFAULT_REGIMES,
  MAX_TRANSITIONS_PER_TICK,
  REGIME_ACTIVITY_SHARE,
  REGIME_DURATIONS,
  REGIME_LADDER,
  REGIME_LEVELS,
  relativeRegimeLevel,
  splitRegimeLevel,
  VOLATILITY_REGIMES,
  VolatilityRegimeModulator,
  weibullSample,
  type RegimeConfig,
  type RegimeSnapshot,
  type RegimeSpec,
  type VolatilityRegime,
} from './regime.js';
export {
  assertStructureConfig,
  DEFAULT_STRUCTURE,
  STRUCTURE_PHASES,
  StructurePhaseModulator,
  type PhaseSpec,
  type StructureConfig,
  type StructurePhase,
  type StructureSnapshot,
} from './structure.js';
export {
  MAX_REPORTED_DIVERGENCES,
  runMirrorTest,
  SignInvertingStream,
  type InteriorRange,
  type MirrorDivergence,
  type MirrorOptions,
  type MirrorResult,
} from './mirror.js';
export {
  assertPersonalitySafe,
  assertPersonalityTraits,
  authorPersonality,
  cascadeInflation,
  cascadeInflationOfClustering,
  cascadeRmsGain,
  cascadeTimescalesMs,
  DEFAULT_TRAITS,
  EXCESS_KURTOSIS_BAND,
  expandPersonality,
  layeredInflation,
  meanRegimeActivity,
  MIN_FASTEST_COMPONENT_TICKS,
  MIN_TICK_RATE_PER_MS,
  otcDispersionFactor,
  predictedExcessKurtosis,
  REGIME_DURATION_FACTOR_RANGE,
  regimeDurationFactor,
  regimeInflation,
  solveClustering,
  structureDistribution,
  structureInflation,
  STRUCTURE_INFLATION_STEPS,
  TailWeightUnreachableError,
  TRAIT_BOUNDS,
  type AuthoredPersonality,
  type PersonalityTraits,
} from './personality.js';
export {
  calibrateAsset,
  calibrateAssetAsync,
  CALIBRATION_CHUNK_TICKS,
  CALIBRATION_HORIZON_MS,
  CALIBRATION_SPAN_MS,
  CALIBRATION_STREAM_PURPOSES,
  rescaleCalibration,
  TARGET_TIE_RATE,
  type AssetDefinition,
  type CalibratedAsset,
  type CalibrationEvidence,
  type CalibrationOptions,
} from './asset.js';
export { personalityConfig } from './personality.js';
export {
  archetypeById,
  assertArchetypeFeasible,
  ASSET_ARCHETYPES,
  KURTOSIS_HEADROOM,
  MEAN_REGIME_ACTIVITY,
  meanIntervalForDispersion,
  provisionalTickRms,
  reachableExcessKurtosis,
  sampleArchetype,
  sampleTraits,
  spacingCeiling,
  SPACING_FEASIBILITY_MARGIN,
  STARTING_CASCADE_INFLATION,
  startingClustering,
  tempoForMeanInterval,
  tempoRangeFor,
  TICK_RATE_PER_ROOT_DISPERSION,
  withDerivedTempo,
  type ArchetypeDefinition,
  type ArchetypeSample,
  type AssetArchetype,
  type Range,
  type SampledTraitRanges,
} from './families.js';
export {
  MINIMUM_TRAIT_DISTANCE,
  traitDistance,
  traitDistanceCheck,
  type TraitDistanceOptions,
} from './differentiation.js';
export {
  dispersionLogSigma,
  dispersionPercent,
  DISPERSION_FIT_TURNOVERS,
  DISPERSION_WINDOW_MS,
  minimumDispersionSpanMs,
} from './dispersion.js';
export { ASSET_SEATS, seatArchetype, seatById, type AssetSeat } from './seats.js';
export {
  HEAVY_SUITE_SAMPLE,
  sampleCatalogue,
  type CatalogueSample,
  type CatalogueSampleOptions,
} from './catalogueSample.js';
export {
  ASSET_CATALOGUE,
  assetById,
  configFor,
  registrationKeyLabel,
  type AuthoringTargets,
  type RegisteredAsset,
} from './catalogue.js';
export {
  ASSET_ID_PATTERN,
  checkAssetId,
  checkIdentity,
  MAX_ASSET_ID_LENGTH,
  MAX_DISPLAY_PRECISION,
  MAX_LABEL_COMPONENT_LENGTH,
  PACE_FIT_PASSES,
  PACE_TOLERANCE,
  REFERENCE_PRICE_BOUNDS,
  registerAsset,
  type DifferentiationCheck,
  type RegistrationOptions,
  type RegistrationOutcome,
  type RegistrationRequest,
  type RegistrationStage,
} from './registration.js';
export {
  selectClose,
  type CloseSelection,
  type CloseSelectionRequest,
  type Reachability,
  selectCloseWhere,
  type ConditionedCloseRequest,
  reachabilityBand,
} from './closeSelection.js';
export {
  type Continuation,
  INTERVENTIONS,
  type InterventionRequest,
  type InterventionResult,
  nextShock,
  selectContinuation,
} from './intervention.js';
