#!/usr/bin/env node
import { writeFileSync } from 'node:fs';
import {
  ASSET_SEATS,
  CALIBRATION_SPAN_MS,
  minimumDispersionSpanMs,
  registerAsset,
  traitDistanceCheck,
  type RegisteredAsset,
} from '@otc/engine';
import { entry, evidenceRow, parse, registrationKeyring, requestFor } from './catalogueBuild.js';

/**
 * Build the catalogue of thirty: draw, author, calibrate and differentiate
 * every seat, and emit the compiled catalogue and its evidence.
 *
 * **PH-26.3.** This is the run that produces `packages/engine/src/catalogue.ts`'s
 * thirty entries. It is a **deliberate act**, not a test: it takes minutes, and
 * its output is a recorded artefact that later work cites.
 * `catalogue.stat.test.ts` re-runs the same calibration on a stratified sample
 * at every gate, so the method stays checked even though the full run does not.
 *
 * Everything decidable without a simulation is in `catalogueBuild.ts` and is
 * unit-tested; what is left here is the simulating and the writing.
 *
 * Usage:
 *   node tools/sim/dist/buildCatalogue.js [--out FILE] [--evidence FILE] [--label NAME]
 *                                         [--seats a,b] [--replicates N]
 */
async function main(): Promise<void> {
  const options = parse(process.argv.slice(2));
  const seats = ASSET_SEATS.filter(
    (seat) => options.seats === null || options.seats.includes(seat.id),
  );
  if (seats.length === 0) throw new Error('No seats selected.');

  const differentiates = traitDistanceCheck();
  const built: RegisteredAsset[] = [];
  const entries: string[] = [];
  const evidence: string[] = [];
  const started = Date.now();

  for (const seat of seats) {
    const seatStarted = Date.now();
    process.stderr.write(`${seat.id}: drawing from ${seat.archetype}\n`);
    const { request, sample, retreats } = requestFor(seat);
    const keyring = registrationKeyring(seat);
    const span = minimumDispersionSpanMs(request.traits);
    const outcome = await registerAsset(request, {
      keyring,
      environment: 'simulation',
      existing: built,
      differentiates,
      // Replicates of a share of the span the dispersion fit needs, combined
      // by median — CA6-26: one realisation puts a 1% quantile of a
      // heavy-tailed variable only within 18.5%.
      // One per cent over the span the fit needs: `span / replicates × replicates`
      // is not `span` in floating point, and the guard is a strict comparison —
      // dogeusdt-otc was refused at "needs 32.0 hours, this calibration spans
      // 32.0" on the first full run.
      // …and never less than the catalogue's own ten-day calibration span. The
      // dispersion fit needs sixteen turnovers of the slowest volatility
      // component, which for a memory of an hour and a half is a day and a
      // bit — enough for σ, far too few thirty-second horizons for a 1%
      // quantile: dogeusdt-otc calibrated at 1.37% against a 1% target on 1.2
      // days × 3. A settlement refund rate is not a number to take from a
      // short run.
      calibration: {
        replicates: options.replicates,
        simulatedMs: Math.ceil(Math.max(span * 1.01, CALIBRATION_SPAN_MS) / options.replicates),
      },
      onStage: (stage) => process.stderr.write(`  ${seat.id}: ${stage}\n`),
    });
    if (outcome.kind !== 'registered') {
      throw new Error(`${seat.id} refused at ${outcome.stage}: ${outcome.reason}`);
    }
    const asset = outcome.asset;
    built.push(asset);
    entries.push(entry(seat, asset));
    const seconds = ((Date.now() - seatStarted) / 1000).toFixed(0);
    evidence.push(
      evidenceRow({
        seat,
        asset,
        sample,
        retreats,
        spanMs: span,
        replicates: options.replicates,
        seconds: Number(seconds),
      }),
    );
    process.stderr.write(
      `${seat.id}: registered in ${seconds}s — quantum ${asset.evidence.logQuantum.toExponential(3)}, ` +
        `precision ${asset.instrument.displayPrecision}, tie ${(asset.evidence.tieRate * 100).toFixed(3)}%\n`,
    );
  }

  const minutes = ((Date.now() - started) / 1000 / 60).toFixed(1);
  const header =
    `// GENERATED by tools/sim/src/buildCatalogue.ts — do not edit by hand.\n` +
    `// Regenerate with: npm run catalogue:build -- --replicates ${String(options.replicates)}\n` +
    `// Keyring: MasterKeyring.forTesting(registrationKeyLabel(id)) per asset, asset label the id. ` +
    `Run label: ${options.label}. Run time: ${minutes} minutes.\n`;
  const body = `${header}\nexport const CATALOGUE_OF_THIRTY_ENTRIES = [\n${entries.join('\n')}\n];\n`;
  if (options.out === null) process.stdout.write(body);
  else writeFileSync(options.out, body, 'utf8');

  const table =
    `| asset | archetype | tail weight drawn → authored | quantum | precision | tie rate | median steps | mean interval ms | calibration | time |\n` +
    `| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${evidence.join('\n')}\n\n` +
    `Keyring: \`MasterKeyring.forTesting(registrationKeyLabel(id))\` per asset. Run label: \`${options.label}\`. ` +
    `Replicates: ${String(options.replicates)}. Total run time: ${minutes} minutes.\n`;
  if (options.evidence !== null) writeFileSync(options.evidence, table, 'utf8');
  else process.stderr.write(`\n${table}`);
}

await main();
